### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by zeeshan-tufail** [quarkiverse/quarkus-cxf#1080]
I'm using the following quarkus platform and dependencies and getting error. Please assist me how to overcome this.

pom.xml snippet:

```
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>3.4.2</quarkus.platform.version>
    <maven.compiler.release>11</maven.compiler.release>

     <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf-rt-features-logging</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.cxf</groupId>
      <artifactId>quarkus-cxf-rt-ws-security</artifactId>
    </dependency>
```
application.properties snippet:

```
quarkus.cxf.codegen.wsdl2java.SMSService.wsdl-location=wsdl/*/SMSPortal_SMSService.wsdl
quarkus.cxf.codegen.wsdl2java.SMSService.package-names=SMSService
%dev.quarkus.cxf.client.SMSService.client-endpoint-url=https://integration/SmsPortalService/kfh/smsportal/webservices/SMSPortal_SMSService.jws
%dev.quarkus.cxf.client.SMSService.service-interface=SMSService.SMSPortalSMSService

quarkus.cxf.client.SMSService.trust-store=microservice.jks ( This file is placed src/main/resources folder)
quarkus.cxf.client.SMSService.trust-store-type=PKCS12
quarkus.cxf.client.SMSService.trust-store-password=xxxx
```
quarkus is running in DEV mode:

```
Caused by: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://integration/SmsPortalService/kfh/smsportal/webservices/SMSPortal_SMSService.jws: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1452)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1433)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:717)
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
```

**Comment by ppalaga** [comment]
Are you sure `microservice.jks` contains all required certs?

Is it really a `PKCS12` trust store? The suffix `.jks` rather reserved for the Java KeyStore format. 
You may want to check using

```
keytool -list -v -keystore src/main/resources/microservice.jks \
    -storepass <password> \
    -storetype PKCS12
```

and compare the output with 

```
openssl s_client -connect <server>:<port>
```

where `<server>:<port>` would be something like `integration:443`.

See also https://stackoverflow.com/questions/65727569/how-to-verify-if-keystore-has-all-the-certificates-needed-to-connect-to-server

**Comment by zeeshan-tufail** [comment]
> Are you sure `microservice.jks` contains all required certs?
    [ZT]: Yes it has all needed certificates.
> 
> Is it really a `PKCS12` trust store? The suffix `.jks` rather reserved for the Java KeyStore format. You may want to check using
> 
  [ZT]: Yest it is PKCS12 store type.
![image](https://github.com/quarkiverse/quarkus-cxf/assets/36452927/7a4c72fc-0a53-4b34-85d9-dbe3de935641)

> ```
> keytool -list -v -keystore src/main/resources/microservice.jks \
>     -storepass <password> \
>     -storetype PKCS12
> ``
  [ZT]: Provided in previous step.
> 
> and compare the output with
> 
> ```
> openssl s_client -connect <server>:<port>
> ```
> 
> where `<server>:<port>` would be something like `integration:443`.
> 
> See also https://stackoverflow.com/questions/65727569/how-to-verify-if-keystore-has-all-the-certificates-needed-to-connect-to-server

I compared and needed certificate available in trust store file

**Comment by zeeshan-tufail** [comment]
I believe the issue is that microservice.jks file was not loaded by using configuration properties.
I overcome this issue by loading the TrustManager programmatically and it's working.

**Comment by zeeshan-tufail** [comment]
Secondly, When I moved to RedHat build of quarkus (v3.2), It's also working by using configuration properties without any manually work (programmatically).

We can close this issue.  Than you so much your support.

**Comment by ppalaga** [comment]
Yeah, the `quarkus.cxf.client.*.trust-*` family of options is rather new. 
I am happy it works for you now!
