### ISSUE TITLE
Quarkus-CXF extension : Could not find target method error when generating native executables using maven native profile (as in the quarkus guides)

### ISSUE THREAD

**Issue by DiegoGutierrezFing** [quarkiverse/quarkus-cxf#1085]
Hi there, i hope you all are doing great.

I'm a quarkus begginer user coming from a Java EE (and some SpringBoot) background. After succesfully compiling, building and running a SOAP webservice application in classic JVM mode using the **quarkus-cxf** extension, i tried generating a **native mode** equivalent executable following the tutorials here:

https://quarkus.io/guides/building-native-image

As you might expect from a newcomer, I´m having some trouble i could not diagnose the underlying cause. This is what happens when compiling a native quarkus application using the native profile:

```shell
mvn clean package -Pnative
```

Which returns an error i don´t know how to interpret:

```shell
Error: Could not find target method: private static java.lang.String io.quarkiverse.cxf.saaj.graal.Traget_javax_xml_soap_FactoryFinder.fromJDKProperties(java.lang.String,java.lang.String)
com.oracle.svm.core.util.UserError$UserException: Could not find target method: private static java.lang.String io.quarkiverse.cxf.saaj.graal.Traget_javax_xml_soap_FactoryFinder.fromJDKProperties(java.lang.String,java.lang.String)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:824)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:441)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:413)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:386)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:342)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:966)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

 As far as i know, the class:

```java
io.quarkiverse.cxf.saaj.graal.Traget_javax_xml_soap_FactoryFinder
```

 seems to be a dummy class whose method:

```java
io.quarkiverse.cxf.saaj.graal.Traget_javax_xml_soap_FactoryFinder.fromJDKProperties(java.lang.String,java.lang.String)
```

only returns "null" :

```java
package io.quarkiverse.cxf.saaj.graal;

import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;

@TargetClass(className = "jakarta.xml.soap.FactoryFinder")
final class Traget_javax_xml_soap_FactoryFinder {

    /**
     * The target method wants to read a properties file under {@code java.home} which does not work on GraalVM (there
     * is no
     * JRE distro at native runtime).
     *
     * @param factoryId
     * @param deprecatedFactoryId
     * @return
     */
    @Substitute
    private static String fromJDKProperties(String factoryId, String deprecatedFactoryId) {
        return null;
    }
}

public class SoapApiSubstitutions {
}
```

Can somebody give me a hint of what the error means, or if possible at all, how to fix it?

Also, in more general terms, Is it possible to generate native executables using the **quarkus.cxf** extension?

If not, is it in the roadmap?

Thanks a lot and greetings from Uruguay
Diego

Edited: corrected some grammar errors

**Comment by ppalaga** [comment]
Let's discuss thin on a single place: https://github.com/quarkiverse/quarkus-cxf/discussions/1086
