### ISSUE TITLE
How to externalize cxf-client truststore.jks file

### ISSUE THREAD

**Issue by zeeshan-tufail** [quarkiverse/quarkus-cxf#1103]
Currently, I placed the trust-store file in src/main/resources path and the reference in quarkus [application.properties](http://application.properties/) file.
But I want to externalize so that it can be configurable w.r.t environment like DEV, UAT, Staging and RPOD and I am using OpenShift for orchestrate the pods.
[application.properties](http://application.properties/) snippet:
quarkus.cxf.client.helloservice.trust-store=microservice.truststore
quarkus.cxf.client.helloservice.trust-store-type=PKCS12
quarkus.cxf.client.helloservice.trust-store-password=${microservice.trust-store}

**Comment by ppalaga** [comment]
The `trust-store` property is first looked up as a classpath resource and if not available there, it is then looked up the filesystem.
OpenShift supports mounting a secret as a file in the container and so the application should be able to find it there in the filesystem. The example 3. [around here](https://docs.openshift.com/container-platform/4.8/nodes/pods/nodes-pods-secrets.html#nodes-pods-secrets-creating_nodes-pods-secrets) shows how to do that.

**Comment by ppalaga** [comment]
For having different values for DEV, UAT, Staging and PROD, it depends how you organize it on OpenShift. If you have separate clusters or namespaces for the individual stages, then I'd suggest using the same path in `application.properties` but mount a secret with a different content on the various clusters/namespaces.

**Comment by zeeshan-tufail** [comment]
Thank you so much. Yes I have two cluster Production and UAT. The UAT OCP having two namespace as DEV and UAT.
Let me review openshift provided link if I need further details will update the ticket.

**Comment by zeeshan-tufail** [comment]
I created the configmap for truststore file and mounted it to the pod But getting below error, I verified the truststore file mounted in the desired file system path.

**application.properties:**
microservice.trust-store=${microservice-truststore-password}
quarkus.cxf.client.SMSService.trust-store=file:/etc/truststore/microservice-truststore.jks
quarkus.cxf.client.SMSService.trust-store-type=JKS

**container :** 
sh-4.4$ cd /etc/truststore/
sh-4.4$ ls
microservice-truststore.jks
sh-4.4$ keytool --list --keystore microservice-truststore.jks -storepass ****
Keystore type: JKS
Keystore provider: SUN
Your keystore contains 1 entry
soaapigw, Dec 5, 2023, trustedCertEntry,
Certificate fingerprint (SHA-256): B1:88:B1:EA:53:49:D1:E0:FC:50:44:5A:51:25:17:BA:11:05:83:E3:4A:CD:70:AB:4F:4B:F7:D9:ED:22:DA:BC
sh-4.4$
 
**error logs**
Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1712)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1370)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1331)
        at rg.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:69)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1383)
        ... 47 more
**Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty**
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)
        at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
        at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        ... 60 more
**Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty**
        at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)
        ... 76 more

**Comment by ppalaga** [comment]
> microservice.trust-store=${microservice-truststore-password}
> quarkus.cxf.client.SMSService.trust-store=file:/etc/truststore/microservice-truststore.jks
> quarkus.cxf.client.SMSService.trust-store-type=JKS

You perhaps forgot to set 

```
quarkus.cxf.client.SMSService.trust-store-password=${microservice-truststore-password}
```
?

Also note that the `trust-store*` family of options is only supported since Quarkus CXF 2.5.0 (and Quarkus Platform 3.5.0).

**Comment by zeeshan-tufail** [comment]
I forget to paste this configuration. It is there in application.properties same as you mentioned.
I'm using RedHat Build of quarkus and platform version [3.2.9.Final-redhat-00002](https://mvnrepository.com/artifact/io.quarkus/quarkus-maven-plugin/3.2.9.Final-redhat-00002)

**Comment by ppalaga** [comment]
> I'm using RedHat Build of quarkus and platform version [3.2.9.Final-redhat-00002](https://mvnrepository.com/artifact/io.quarkus/quarkus-maven-plugin/3.2.9.Final-redhat-00002)

Yep, unfortunately, the `trust-store*` family of options is not available in Quarkus CXF 2.2.x (and Quarkus Platform 3.2.x).
You would have to configure the trust store via CDI, like we do in this integration test: https://github.com/quarkiverse/quarkus-cxf/blob/2.2/integration-tests/ws-security-policy/src/main/java/io/quarkiverse/cxf/it/security/policy/Init.java
In the test, the properties are defined in application.properties : https://github.com/quarkiverse/quarkus-cxf/blob/2.2/integration-tests/ws-security-policy/src/main/resources/application.properties#L3-L6 You might want to defined them in an Openshift secret.

**Comment by zeeshan-tufail** [comment]
I tried as mentioned above link (CDI approach) but no success, facing same error as below
**Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty**

**Comment by zeeshan-tufail** [comment]
I have created support ticket and response that quarkus-cxf is not supported by redhat and directed me to use camel-cxf extension instead.

**Comment by ppalaga** [comment]
> I have created support ticket and response that quarkus-cxf is not supported by redhat and directed me to use camel-cxf extension instead.

No, that information is not correct. Quarkus CXF is supported through a product called "Red Hat build of Apache Camel for Quarkus" (the old name is "Red Hat Integation").

I can help here anyway. Could you please provide a basic reproducer?

**Comment by ppalaga** [comment]
Please feel free to reopen if needed.
