### ISSUE TITLE
Error building native executable: Discovered unresolved type during parsing: org.conscrypt.Conscrypt

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-cxf#1132]
I have an odd error that happens when building a native executable. As a JAR everything seems to work fine.

The error I get is:
```
Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
```

Would this have to deal with:

```
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
```

The full output is:
```
========================================================================================================================
GraalVM Native Image: Generating 'services-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                   (14.9s @ 0.46GB)
 Java version: 21.0.1+12-LTS, vendor version: Mandrel-23.1.1.0-Final
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 5 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.hibernate.validator.runtime.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.validator.internal.util.Version] categories
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
------------------------------------------------------------------------------------------------------------------------
 5 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:IncludeResourceBundles' (origin(s): 'META-INF/native-image/org.eclipse/yasson/native-image.properties' in 'file:///project/lib/org.eclipse.yasson-3.0.3.jar')
 - '-H:ReflectionConfigurationResources' (origin(s): 'META-INF/native-image/io.netty/netty-transport/native-image.properties' in 'file:///project/lib/io.netty.netty-transport-4.1.100.Final.jar')
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 11.64GB of memory (75.6% of 15.40GB system memory, determined at start)
 - 12 thread(s) (100.0% of 12 available processor(s), determined at start)
[2/8] Performing analysis...  [********]                                                                (85.5s @ 3.88GB)
   26,622 reachable types   (85.1% of   31,271 total)
   45,340 reachable fields  (67.8% of   66,869 total)
  155,073 reachable methods (63.9% of  242,634 total)
    9,376 types, 2,156 fields, and 29,198 methods registered for reflection
       76 types,   180 fields, and   136 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z

Error: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  trying to constant fold static field org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.RND_GEN
    at org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52)
  parsing method org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52) reachable via the parsing context
    at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.applyParameters(ConscryptClientTlsStrategy.java:90)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$0(AbstractClientTlsStrategy.java:138)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22000.initialize(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.initialize(SSLIOSession.java:293)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.beginHandshake(SSLIOSession.java:268)
   at org.apache.hc.core5.reactor.InternalDataChannel.startTls(InternalDataChannel.java:258)
   at org.apache.hc.client5.http.impl.nio.DefaultManagedAsyncClientConnection.startTls(DefaultManagedAsyncClientConnection.java:158)
   at org.apache.hc.core5.http.nio.ssl.BasicClientTlsStrategy.upgrade(BasicClientTlsStrategy.java:108)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:116)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:107)
   at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
   at org.apache.hc.core5.pool.StrictConnPool.fireCallbacks(StrictConnPool.java:397)
   at org.apache.hc.core5.pool.StrictConnPool.close(StrictConnPool.java:139)
   at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager.close(PoolingAsyncClientConnectionManager.java:229)
   at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.internalClose(InternalAbstractHttpAsyncClient.java:125)
   at org.apache.hc.client5.http.impl.async.AbstractHttpAsyncClientBase.close(AbstractHttpAsyncClientBase.java:115)
   at org.apache.hc.client5.http.impl.async.InternalHttpAsyncClient.close(InternalHttpAsyncClient.java:67)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.shutdown(AsyncHTTPConduitFactory.java:299)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.close(AsyncHTTPConduitFactory.java:450)
   at root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.createTlsDetails(ConscryptClientTlsStrategy.java:101)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:149)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22220.verify(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
   at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
   at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.processPendingChannels(SingleCoreIOReactor.java:220)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:137)
   at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
   at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
   at java.lang.Thread.runWith(Thread.java:1596)
   at java.lang.Thread.run(Thread.java:1583)
   at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
   at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
   at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)
   at static root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  trying to constant fold static field org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.RND_GEN
    at org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52)
  parsing method org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52) reachable via the parsing context
    at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.applyParameters(ConscryptClientTlsStrategy.java:90)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$0(AbstractClientTlsStrategy.java:138)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22000.initialize(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.initialize(SSLIOSession.java:293)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.beginHandshake(SSLIOSession.java:268)
   at org.apache.hc.core5.reactor.InternalDataChannel.startTls(InternalDataChannel.java:258)
   at org.apache.hc.client5.http.impl.nio.DefaultManagedAsyncClientConnection.startTls(DefaultManagedAsyncClientConnection.java:158)
   at org.apache.hc.core5.http.nio.ssl.BasicClientTlsStrategy.upgrade(BasicClientTlsStrategy.java:108)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:116)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:107)
   at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
   at org.apache.hc.core5.pool.StrictConnPool.fireCallbacks(StrictConnPool.java:397)
   at org.apache.hc.core5.pool.StrictConnPool.close(StrictConnPool.java:139)
   at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager.close(PoolingAsyncClientConnectionManager.java:229)
   at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.internalClose(InternalAbstractHttpAsyncClient.java:125)
   at org.apache.hc.client5.http.impl.async.AbstractHttpAsyncClientBase.close(AbstractHttpAsyncClientBase.java:115)
   at org.apache.hc.client5.http.impl.async.InternalHttpAsyncClient.close(InternalHttpAsyncClient.java:67)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.shutdown(AsyncHTTPConduitFactory.java:299)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.close(AsyncHTTPConduitFactory.java:450)
   at root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.createTlsDetails(ConscryptClientTlsStrategy.java:101)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:149)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22220.verify(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
   at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
   at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.processPendingChannels(SingleCoreIOReactor.java:220)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:137)
   at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
   at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
   at java.lang.Thread.runWith(Thread.java:1596)
   at java.lang.Thread.run(Thread.java:1583)
   at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
   at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
   at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)
   at static root method.(Unknown Source)


        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  trying to constant fold static field org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.RND_GEN
    at org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52)
  parsing method org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.access$2300(NTLMEngineImpl.java:52) reachable via the parsing context
    at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.applyParameters(ConscryptClientTlsStrategy.java:90)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$0(AbstractClientTlsStrategy.java:138)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22000.initialize(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.initialize(SSLIOSession.java:293)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.beginHandshake(SSLIOSession.java:268)
   at org.apache.hc.core5.reactor.InternalDataChannel.startTls(InternalDataChannel.java:258)
   at org.apache.hc.client5.http.impl.nio.DefaultManagedAsyncClientConnection.startTls(DefaultManagedAsyncClientConnection.java:158)
   at org.apache.hc.core5.http.nio.ssl.BasicClientTlsStrategy.upgrade(BasicClientTlsStrategy.java:108)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:116)
   at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.completed(DefaultAsyncClientConnectionOperator.java:107)
   at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
   at org.apache.hc.core5.pool.StrictConnPool.fireCallbacks(StrictConnPool.java:397)
   at org.apache.hc.core5.pool.StrictConnPool.close(StrictConnPool.java:139)
   at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager.close(PoolingAsyncClientConnectionManager.java:229)
   at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient.internalClose(InternalAbstractHttpAsyncClient.java:125)
   at org.apache.hc.client5.http.impl.async.AbstractHttpAsyncClientBase.close(AbstractHttpAsyncClientBase.java:115)
   at org.apache.hc.client5.http.impl.async.InternalHttpAsyncClient.close(InternalHttpAsyncClient.java:67)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.shutdown(AsyncHTTPConduitFactory.java:299)
   at org.apache.cxf.transport.http.asyncclient.hc5.AsyncHTTPConduitFactory.close(AsyncHTTPConduitFactory.java:450)
   at root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.conscrypt.Conscrypt. This error is reported at image build time because class org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.hc.client5.http.ssl.ConscryptClientTlsStrategy.createTlsDetails(ConscryptClientTlsStrategy.java:101)
Parsing context:
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:149)
   at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy$$Lambda/0x00000007c4c22220.verify(Unknown Source)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
   at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
   at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
   at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.processPendingChannels(SingleCoreIOReactor.java:220)
   at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:137)
   at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
   at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
   at java.lang.Thread.runWith(Thread.java:1596)
   at java.lang.Thread.run(Thread.java:1583)
   at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
   at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
   at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)
   at static root method.(Unknown Source)


        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
        ... 6 more
```

I do have this added for the Async generation:
```
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-transports-http-hc5</artifactId>
    <version>${apache.cxf.version}</version>
</dependency>
```

Quarkus: 3.6.1
Quarkus CXF: 2.6.1
CXF: 4.0.3

**Comment by kjq** [comment]
Totally my fault.  Didn't realize there was a Quarkus CXF BOM _and_ Quarkus CXF HTTP HC5 dependency.

Changing to this below seems to resolve building the native executable but now I am wrestling with the XMX for the build.

```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-cxf-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

And this...

```xml
<dependency>
    <groupId>io.quarkiverse.cxf</groupId>
    <artifactId>quarkus-cxf</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkiverse.cxf</groupId>
    <artifactId>quarkus-cxf-rt-transports-http-hc5</artifactId>
</dependency>
```
