### ISSUE TITLE
ServletController is null when executing CxfHandler.handle(RoutingContext event)

### ISSUE THREAD

**Issue by matheusdallrosa** [quarkiverse/quarkus-cxf#117]
Hello, i have an issue when i try to make a client SOAP request. 

I have generated the java code from a WSDL using the cxf-codegen-plugin from org.apache.cxf, and now i am trying
to make a SOAP request. Inside my resource i have injected the interface which is annotated with @WebService, the interface was created by the plugin i have mentioned. When i make an HTTP request to my resource, even before the code inside the endpoint starts to be executed, i got a NullPointerException here: io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:249)
I opened the debugger in some points of the stack trace and i was able to see that the following property was not initialized.

    private ServletController controller;

I have also seen this waning logs on quarkus startup:
2021-02-03 15:30:47,973 WARN  [io.qua.cxf.CXFRecorder] (Quarkus Main Thread) recorder CXFClientInfoSupplier
2021-02-03 15:30:47,973 WARN  [io.qua.cxf.CXFServletInfos] (Quarkus Main Thread) new CXFServletInfos
2021-02-03 15:30:47,974 WARN  [io.qua.cxf.tra.CxfHandler] (Quarkus Main Thread) no info transmit to servlet

Stack trace:

    java.lang.NullPointerException
        at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:249)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:193)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:38)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

I have not put any code here because i have a lot of SOAP contract from a client inside it, if you need it i think can i try to make some from my own.

Thank you.

**Comment by matheusdallrosa** [comment]
It seems like my issue totally releates to #[93](https://github.com/quarkiverse/quarkus-cxf/issues/93).
I am using version 0.3 as well and the stack trace i am receiving is the same as mentioned.
When will the pull request https://github.com/quarkiverse/quarkus-cxf/pull/95 be available in some release?

**Comment by dufoli** [comment]
so it mean that cxfServletInfos is empty.
Can you post your configuration ? application.properties.  I think it come from path or implementor is missing... So as said in previous comment, it must been fixed by #95 #93

**Comment by matheusdallrosa** [comment]
I don't have the implementor of a @WebService interface since i am only using the client. I think that #95 will really solve the problem since the stack is exactly the same as the issue #93 .

Here is my application.properties:
quarkus.cxf.endpoint."/soap/action/endpoint".client-endpoint-url=http://localhost:8000/
quarkus.cxf.endpoint."/soap/action/endpoin".service-interface=br.com.prototype.SoapService

**Comment by dufoli** [comment]
can you retry with last version 0.4 released today ?

**Comment by matheusdallrosa** [comment]
I have just tried it and it worked. Thank you.
