### ISSUE TITLE
UnsatisfiedResolutionException with server features / interceptors for non-cdi beans

### ISSUE THREAD

**Issue by jakubpietrzak96** [quarkiverse/quarkus-cxf#134]
I am currently unable to register server features or interceptors. For the client it seems to work fine.

Example (LoggingFeature provided by cxf):
```
quarkus.cxf.endpoint.*.features=org.apache.cxf.ext.logging.LoggingFeature
```

This seems to be similar to point 3. mentioned [here](https://github.com/quarkiverse/quarkus-cxf/issues/53#issuecomment-733956826) and partially fixed with #65 (but not for server).

Here is the error that is being thrown:
```
ERROR [i.q.r.Application] (Quarkus Main Thread) Failed to start application (with profile dev): javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class foo.TestInterceptor] and qualifiers [[]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
        at io.quarkiverse.cxf.transport.CxfHandler.getInstance(CxfHandler.java:163)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:124)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:123)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute-1341485114.deploy_0(QuarkusCxfProcessor$startRoute-1341485114.zig:237)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute-1341485114.deploy(QuarkusCxfProcessor$startRoute-1341485114.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:719)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

To me an obvious culprit lies [here](https://github.com/quarkiverse/quarkus-cxf/blob/f64a893ca01d70539e7ec25fe962682e65192799/runtime/src/main/java/io/quarkiverse/cxf/transport/CxfHandler.java#L163)

```java
Object res = CDI.current().select(classObj).get();
```
That line throws `UnsatisfiedResolutionException` when it does which is not expected here.

That method could be modified to either check result of `isResolvable()` call on the CDI instance or check if the `UnsatisfiedResolutionException` is being thrown and act accordingly.
E.g like this:
```java
    private Object getInstance(String className) {
        Class<?> classObj = loadClass(className);
        try {
            return CDI.current().select(classObj).get();
        } catch (UnsatisfiedResolutionException e) {
            // silent fail
        }
        try {
            return classObj.getConstructor().newInstance();
        } catch (ReflectiveOperationException | RuntimeException e) {
            return null;
        }
    }
```

**Comment by shumonsharif** [comment]
I think a PR would be good for this.
