### ISSUE TITLE
Missing dependency for OpenTelemetryCustomizer when OTEL is globally disabled

### ISSUE THREAD

**Issue by wilvdb** [quarkiverse/quarkus-cxf#1476]
We have an application that uses OTEL but not in dev mode. I tried to disable it globally and, for my SOAP clients :
**application.yaml** :

```
%dev.quarkus.otel.enabled=false
%dev.quarkus.cxf.client.myclient.otel.enabled=false
```

And we get the below stacktrace:
```
2024-08-19 10:10:59,465 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-08-19 10:10:59,881 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.opentelemetry.api.OpenTelemetry and qualifiers [@Default]
	- injection target: io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer#openTelemetry
	- declared on CLASS bean [types=[io.quarkiverse.cxf.CxfClientProducer$ClientFactoryCustomizer, io.quarkiverse.cxf.transport.CxfHandler$EndpointFactoryCustomizer, java.lang.Object, io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1546)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

This behavior is explained by the fact that ```quarkus.cxf.client.client-name.otel.enabled``` is not a build time property, contrary to ```quarkus.otel.enabled```.
Should it be possible to check properties ```quarkus.otel.enabled``` and ```quarkus.otel.sdk.disabled``` at build time to avoid ```OpenTelemetryCustomizer``` injection ?

**Comment by ppalaga** [comment]
Thanks for the report, @wilvdb!

> Should it be possible to check properties `quarkus.otel.enabled` and `quarkus.otel.sdk.disabled` at build time to avoid `OpenTelemetryCustomizer` injection ?

Yes, this sounds reasonable. Let me write a test and see whether it will work as expected.

**Comment by ppalaga** [comment]
I do not see `quarkus.otel.sdk.disabled` to cause any harm. I guess the spans won't be available, but that's expected. Why do you think we need to care for `quarkus.otel.sdk.disabled`?

**Comment by ppalaga** [comment]
@wilvdb, any chance to test the fix in https://github.com/quarkiverse/quarkus-cxf/pull/1479 before I release 3.14.0 tomorrowish?
