### ISSUE TITLE
error during native build: No instances of java.awt.color.ICC_ColorSpace 

### ISSUE THREAD

**Issue by neXus1987** [quarkiverse/quarkus-cxf#157]
Hi,
 

Version: 0.5

when generating a native build i got following error, so apache cxf tries to initialize Java Color:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.awt.color.ICC_ColorSpace are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.awt.color.ICC_ColorSpace.
Trace: 
	at parsing com.sun.imageio.plugins.jpeg.JPEGImageReader.checkColorConversion(JPEGImageReader.java:1042)
Call path from entry point to com.sun.imageio.plugins.jpeg.JPEGImageReader.checkColorConversion(BufferedImage, ImageReadParam): 
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkColorConversion(JPEGImageReader.java:984)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1154)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110)
	at javax.imageio.ImageIO.read(ImageIO.java:1468)
	at javax.imageio.ImageIO.read(ImageIO.java:1363)
	at org.apache.cxf.jaxws.interceptors.SwAInInterceptor.handleMessage(SwAInInterceptor.java:110)
	at org.apache.cxf.jaxws.interceptors.SwAInInterceptor.handleMessage(SwAInInterceptor.java:42)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:278)
	at org.apache.cxf.ws.addressing.impl.InternalContextUtils$1.run(InternalContextUtils.java:319)
```

**Comment by shumonsharif** [comment]
@neXus1987 I believe this is unrelated to CXF or this extension, this should be helpful for you:  `https://github.com/quarkusio/quarkus/issues/12535#issuecomment-782354941`

**Comment by neXus1987** [comment]
Yes works, thanks! can be closed.
