### ISSUE TITLE
native build fails

### ISSUE THREAD

**Issue by LorenzoBono** [quarkiverse/quarkus-cxf#172]
native build fails cause of com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput from 
org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02

`initialized without the native-image initialization instrumentation and the stack trace can't be t
racked. Try avoiding to initialize the class that caused initialization of com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput has been initialized without the native-image initialization instrumentation and the stack trace can't be t
racked. Try avoiding to initialize the class that caused initialization of com.sun.xml.bind.v2.runtime.output.FastInfosetStreamWriterOutput

        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:39 min
[INFO] Finished at: 2021-03-04T21:50:38+01:00
[INFO] ------------------------------------------------------------------------
`

maven dependency tree shows

\- io.quarkiverse.cxf:quarkus-cxf:jar:0.5:compile
[INFO]    +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.4.2:compile
[INFO]    |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO]    |  +- org.ow2.asm:asm:jar:9.0:compile
[INFO]    |  +- org.apache.cxf:cxf-core:jar:3.4.2:compile
[INFO]    |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.4.2:compile
[INFO]    |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.4.2:compile
[INFO]    |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO]    |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.4.2:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.4.2:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.4.2:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-ws-addr:jar:3.4.2:compile
[INFO]    |  |  \- org.apache.cxf:cxf-rt-ws-policy:jar:3.4.2:compile
[INFO]    |  |     \- org.apache.neethi:neethi:jar:3.1.1:compile
[INFO]    |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO]    |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO]    +- jakarta.servlet:jakarta.servlet-api:jar:4.0.3:compile
[INFO]    +- org.apache.cxf:cxf-rt-transports-http:jar:3.4.2:compile
[INFO]    +- io.quarkus:quarkus-jaxb:jar:1.12.0.Final:compile
[INFO]    +- io.quarkus:quarkus-jaxp:jar:1.12.0.Final:compile
[INFO]    +- io.quarkus:quarkus-jackson:jar:1.12.0.Final:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.1:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.1:compile
[INFO]    |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.1:compile
[INFO]    +- io.quarkus:quarkus-undertow:jar:1.12.0.Final:compile
[INFO]    |  +- io.quarkus.http:quarkus-http-servlet:jar:3.0.18.Final:compile
[INFO]    |  +- io.quarkus.http:quarkus-http-vertx-backend:jar:3.0.18.Final:compile
[INFO]    |  |  \- io.quarkus.http:quarkus-http-http-core:jar:3.0.18.Final:compile
[INFO]    |  \- io.quarkus.http:quarkus-http-core:jar:3.0.18.Final:compile
[INFO]    |     \- io.netty:netty-codec-http:jar:4.1.49.Final:compile
[INFO]    +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO]    **\- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile**
[INFO]       +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile
[INFO]       \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile

**Comment by shumonsharif** [comment]
Hey @LorenzoBono I'm unable to recreate this issue ... do you have a reproducer project available, by any chance?

**Comment by LorenzoBono** [comment]
Finally im able to make a native build. Im using a delivery of a "soap ws client". I had to exclude all java ws libs an now its working. But on running the APP i got a Nullpointer 

If you have any idea whats could be the reason im glad for any hint. Otherwhise thanks again for the support and the great quarkiverse plugin.

`2021-03-07 22:25:45,505 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
	at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:85)
	at org.apache.cxf.jaxws.ServiceImpl.initializePorts(ServiceImpl.java:217)
	at org.apache.cxf.jaxws.ServiceImpl.initialize(ServiceImpl.java:160)
	at org.apache.cxf.jaxws.ServiceImpl.<init>(ServiceImpl.java:128)
	at org.apache.cxf.jaxws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:82)
	at javax.xml.ws.Service.<init>(Service.java:82)`

**Comment by shumonsharif** [comment]
Hi @LorenzoBono Glad you got it working!  Not sure what may be causing the NPE, but looking at the source for `WSDLServiceFactory`, I would guess you may have some project configuration issue.  Closing this issue for now, but please feel free to open a new issue with a sample project that demonstrates the NPE, will be happy to try to help.

**Comment by pantaoran** [comment]
Hi @LorenzoBono , I have the same problem you described in this issue. Last time you wrote: "I had to exclude all java ws libs an now its working."
What did you mean by "exclude"? Exclude from what?

**Comment by shumonsharif** [comment]
@pantaoran I'm happy to help if you are able to share a sample project which demonstrates the issue.
