### ISSUE TITLE
Native Compiles but does not work missing  com.sun.xml.internal.ws.spi.ProviderImpl

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-cxf#199]
I am testing the CXF Quarkus extension with:

- Quarkus 1.13.2
- CXF 3.4.3
- CXF Quarkus 0.5
- JDK11

Running in dev mode or the jar build works fine but after building a native image it fails with:

`RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.jboss.resteasy.spi.ApplicationException: javax.xml.ws.WebServiceException: Provider com.sun.xml.internal.ws.spi.ProviderImpl not found`

```
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.ws.spi.ProviderImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:281)
        at javax.xml.ws.spi.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:60)
        at javax.xml.ws.spi.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:93)
        at javax.xml.ws.spi.ServiceLoaderUtil.newInstance(ServiceLoaderUtil.java:71)
        ... 66 more
```

I am guessing this has something to do with me missing a dependency or the fact I am building on JDK11 and that is not available.

I am pretty much using the POM's in this project as the basis.

The only significant changes in my POM are the inclusions of RESTEasy with Reactive (I call the service inside a reactive method and this works in dev or jar builds):

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-mutiny</artifactId>
        </dependency>
```

Any suggestions?

**Comment by shumonsharif** [comment]
@kjq Your issue is likely specific to your setup / configuration; the builds for the project are passing fine on JDK 11.  It'll be difficult to provide any suggestions without a reproducer that demonstrates your issue.  

You may have some luck going through the [other GitHub projects that depend on Quarkus CXF](https://github.com/quarkiverse/quarkus-cxf/network/dependents), there are many that use JDK 11.

**Comment by henrikcaesar** [comment]
I ran into the same fault using
- Quarkus 1.13.3
- CXF 3.4.3
- CXF Quarkus 0.6
- JDK11

> ~/git/quarkus-cxf-199 main ❯ mvn -version                                                                                                                                                                                    2m 52s 08:57:48
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"

Managed to reproduce the fault in https://github.com/henrikcaesar/quarkus-cxf-199, @shumonsharif can you try running the tests?

**Comment by shumonsharif** [comment]
Thanks @henrikcaesar for the reproducer.  There were a number of changes I needed to make to get the native mode working in your project.  The major updates / changes are listed below and I've attached the necessary [changes.zip](https://github.com/quarkiverse/quarkus-cxf/files/6444938/changes.zip); let me know if any questions and whether this addresses the issues you were seeing.

- Create src/main/resources/META-INF/services/javax.xml.ws.spi.Provider with content `org.apache.cxf.jaxws.spi.ProviderImpl`
- Create src/main/resources/reflection-config.json file for:  `org.apache.cxf.jaxws.spi.ProviderImpl`, `com.sun.xml.bind.v2.JAXBContextFactory`, and the web service implementation class itself, `org.acme.server.HelloEndpointImpl`
- Create src/main/resources/resources-config.json file for various resource files contained in JARs, as well as the WSDL file for hello service
- Add the following to pom.xml:  `<quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime,--enable-url-protocols=jar,-H:ResourceConfigurationFiles=resources-config.json,-H:ReflectionConfigurationFiles=reflection-config.json</quarkus.native.additional-build-args>`

@dufoli please review the list above - I think some of these may be possible to address in the extension - let me know if you have any thoughts!

**Comment by dufoli** [comment]
Many thanks @shumonsharif for your hard work. It will help a lot!
