### ISSUE TITLE
javax.transaction classloading conflict caused by geronimo-jta_1.1_spec

### ISSUE THREAD

**Issue by famod** [quarkiverse/quarkus-cxf#219]
A colleague of mine ran into this while trying to integrate `quarkus-cxf` 0.7 into our current project:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization for class io.agroal.pool.util.XAConnectionAdaptor: when selecting method 'javax.transaction.xa.XAResource javax.sql.XAConnection.getXAResource()' the class loader 'platform' for super interface javax.sql.XAConnection, and the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @12329ae9 of the selected method's class, io.agroal.pool.util.XAConnectionAdaptor have different Class objects for the type javax.transaction.xa.XAResource used in the signature (javax.sql.XAConnection is in module java.sql of loader 'platform'; io.agroal.pool.util.XAConnectionAdaptor is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @12329ae9, parent loader io.quarkus.bootstrap.classloading.QuarkusClassLoader$GetPackageBlockingClassLoader @1853ff0e)
```
This is from a surefire run, hence the condensed error trace. We only need the client feature.

So there is basically a classpath conflict with respect to `javax.transaction`.

Turns out this problem vanishes once I exclude `geronimo-jta_1.1_spec`:
```xml
<dependency>
    <groupId>io.quarkiverse.cxf</groupId>
    <artifactId>quarkus-cxf</artifactId>
    <version>${quarkus-cxf.version}</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.geronimo.specs</groupId>
            <artifactId>geronimo-jta_1.1_spec</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

I have yet to check what this dependency is used for excatly in `cxf-rt-frontend-jaxws`:
```
[INFO] +- io.quarkiverse.cxf:quarkus-cxf:jar:0.7:compile
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.4.3:compile
[INFO] |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:3.4.3:compile
[INFO] |  |  |  +- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
[INFO] |  |  |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.4.3:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.4.3:compile
[INFO] |  |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-ws-addr:jar:3.4.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-policy:jar:3.4.3:compile
[INFO] |  |  |     \- org.apache.neethi:neethi:jar:3.1.1:compile
[INFO] |  |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.2:runtime
[INFO] |  |  |  \- org.jvnet.staxex:stax-ex:jar:1.8.3:runtime
[INFO] |  |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO] |  +- jakarta.servlet:jakarta.servlet-api:jar:4.0.3:compile
[INFO] |  +- org.apache.cxf:cxf-rt-transports-http:jar:3.4.3:compile
[INFO] |  \- io.quarkus:quarkus-jaxp:jar:1.13.2.Final:compile
```

I'll gladly create a PR for this but I'd like to hear some opinions first. Thanks!

**Comment by famod** [comment]
Btw, existing extensions in our app:
```
Installed features: [agroal, blaze-persistence, cdi, config-yaml, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-h2, jdbc-mariadb, liquibase, mutiny, narayana-jta, oidc-client, oidc-client-filter, oidc-token-propagation, rest-client, rest-client-jackson, resteasy-reactive, resteasy-reactive-jackson, security, smallrye-context-propagation, smallrye-openapi, spring-data-jpa, spring-di, swagger-ui]
```

**Comment by dufoli** [comment]
I do not understand the error log talk about agroal and then it is linked to cxf very odd...

**Comment by dufoli** [comment]
ok got it. quarkus use another micro profile/ jakarta lib so we end up with conflict. So, the solution you proposed by excluding lib seems good to me. I just do not understand why log talked about agroal....

**Comment by shumonsharif** [comment]
I believe the issue is that CXF and Agroal are each depending on different versions of the geronimo libraries... both libraries end up on the classpath, resulting in the conflict during runtime.  I'm not entirely sure what CXF uses from geronimo, but this [older release page](http://cxf.apache.org/apache-cxf-230-release-notes.html) appears to say it's used for "General CXF Usage, JAX-WS Support".  So fully agree with @dufoli , the best option is to just exclude it as you already are doing - would not advise that we do so in the extension as even if we're not leveraging it today we may do so later.

**Comment by famod** [comment]
FWIW, this is the full stacktrace:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:674)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:747)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:959)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:212)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:331)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:643)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:689)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
        ... 34 more
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization for class io.agroal.pool.util.XAConnectionAdaptor: when selecting method 'javax.transaction.xa.XAResource javax.sql.XAConnection.getXAResource()' the class loader 'platform' for super interface javax.sql.XAConnection, and the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @32f55070 of the selected method's class, io.agroal.pool.util.XAConnectionAdaptor have different Class objects for the type javax.transaction.xa.XAResource used in the signature (javax.sql.XAConnection is in module java.sql of loader 'platform'; io.agroal.pool.util.XAConnectionAdaptor is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @32f55070, parent loader io.quarkus.bootstrap.classloading.QuarkusClassLoader$GetPackageBlockingClassLoader @6f7c4bd5)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by famod** [comment]
> I believe the issue is that CXF and Agroal are each depending on different versions of the geronimo libraries...

It's not geronimo, it's different jars providing `javax.transaction.xa.*` (or better to say `javax.transaction`).

In our case there is also:
```
[INFO] +- io.quarkus:quarkus-hibernate-orm:jar:1.13.2.Final:compile
[...]
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
```
So you have the Quarkus-typical jakarta jar, brought in by e.g. Hibernate, but also the geronimo jar that is brought in by CXF.
Note: From version 2.0.0 on the package is `jakarta.[...]`, not ``javax.[...]`.

So TBH, users of `quarkus-cxf` will probably hit this problem very often, as soon as they have Hibernate or something else in the mix that brings in `javax.transaction`.
I'll try to proove that with a Quarkus quickstart.

So I don't think that doing nothing is an option, TBH.

**Comment by famod** [comment]
FWIW, core extensions bringing in that jakarta tx lib:
```
$ grep -R --include=pom.xml 'jakarta.transaction-api' extensions/
extensions/agroal/runtime/pom.xml:            <artifactId>jakarta.transaction-api</artifactId>
extensions/quartz/runtime/pom.xml:            <artifactId>jakarta.transaction-api</artifactId>
extensions/hibernate-orm/runtime/pom.xml:            <artifactId>jakarta.transaction-api</artifactId>
extensions/narayana-jta/runtime/pom.xml:            <artifactId>jakarta.transaction-api</artifactId>
extensions/infinispan-client/runtime/pom.xml:            <artifactId>jakarta.transaction-api</artifactId>
```

**Comment by famod** [comment]
> but this older release page appears to say it's used for "General CXF Usage, JAX-WS Support"

Geronimo is (well, was) much more than just JTA, it was a full app server.
Anyway, CXF today references geronimo only for:
- JMS transport: https://cxf.apache.org/docs/jms-transactions.html
- some OIDC stuff but in the "rs" part which is not SOAP
- (and I also found traces in osgi/karaf wich is totally out of scope for Quarkus IMO)

```
$ grep -R --include=pom.xml 'geronimo-jta'
rt/transports/jms/pom.xml:            <artifactId>geronimo-jta_1.1_spec</artifactId>
rt/transports/jms/pom.xml:                    <artifactId>geronimo-jta_1.0.1B_spec</artifactId>
rt/transports/jms/pom.xml:                    <artifactId>geronimo-jta_1.0.1B_spec</artifactId>
rt/rs/security/sso/oidc/pom.xml:      <artifactId>geronimo-jta_1.1_spec</artifactId>
systests/uncategorized/pom.xml:                    <artifactId>geronimo-jta_1.0.1B_spec</artifactId>
systests/transport-jms/pom.xml:                    <artifactId>geronimo-jta_1.0.1B_spec</artifactId>
distribution/src/main/release/samples/pom.xml:                    <artifactId>geronimo-jta_1.1_spec</artifactId>
parent/pom.xml:                <artifactId>geronimo-jta_1.1_spec</artifactId>
parent/pom.xml:                        <artifactId>geronimo-jta_1.0.1B_spec</artifactId>
parent/pom.xml:                    <artifactId>geronimo-jta_1.1_spec</artifactId>
```

More info:
- https://issues.apache.org/jira/browse/CXF-8117
- https://issues.apache.org/jira/browse/CXF-8389?jql=project%20%3D%20CXF%20AND%20text%20~%20geronimo%20ORDER%20BY%20key%20DESC

**Comment by dufoli** [comment]
hmm seems reasonable to add  exclusion on 
org.apache.cxf:cxf-rt-frontend-jaxws inside the pom of quarkus cxf
and add dependency to have same than other extension.
Does it sounds right ?

so pom will contain:

```
<dependency>
    <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-rt-frontend-jaxws</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.geronimo.specs</groupId>
            <artifactId>geronimo-jta_1.1_spec</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
</dependency>
```

**Comment by famod** [comment]
> Does it sounds right ?

Yes, I think so.

> so pom will contain

TBH, I would not specifiy `jakarta.transaction-api` unless you are 100% sure that it will work with CXF JMS.
If CXF fails because it cannot find the package: ok, then you'll have to add it anyway.
But if the "regular" usage doesn't require it and as long this extensions does not provide JMS support (in the sense of having an integration test for it), then I personally would _not_ add_ it. Otherwise you would pretend something you didn't test. My 2 cents...

**Comment by shumonsharif** [comment]
The existing pom already currently contains some exclusions for cxf-rt-frontend-jaxws.  We really should just add the new exclusion to the existing list.

So should end up looking like:

```xml
            <dependency>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-rt-frontend-jaxws</artifactId>
                <version>${cxf.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.xml.soap</groupId>
                        <artifactId>javax.xml.soap-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>jakarta.xml.bind</groupId>
                        <artifactId>jakarta.xml.bind-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.geronimo.specs</groupId>
                        <artifactId>geronimo-jta_1.1_spec</artifactId>
                    </exclusion>                    
                </exclusions>
            </dependency>
```

**Comment by famod** [comment]
Thanks @shumonsharif & @dufoli

**Comment by famod** [comment]
Unfortunately, this dependency is still present in 0.8. Can you please reopen this issue @shumonsharif or @dufoli?

I'll come up with a PR fixing this for good!

**Comment by shumonsharif** [comment]
Sounds good @famod I just reopened it!
