### ISSUE TITLE
Quarkiverse Documentation generation is broken

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-cxf#268]
The quarkiverse docs generation is failing with:

```
Error: Duplicate nav in dev@quarkus-cxf: modules/ROOT/nav.adoc
  1: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-cxf.git (ref: master)
  2: docs/modules/ROOT/nav.adoc in https://github.com/quarkiverse/quarkus-cxf.git (ref: v0.9)
    at ContentCatalog.addFile (/usr/local/share/.config/yarn/global/node_modules/@antora/content-classifier/lib/content-catalog.js:126:17)
    at files.forEach (/usr/local/share/.config/yarn/global/node_modules/@antora/content-classifier/lib/classify-content.js:26:78)
    at Array.forEach (<anonymous>)
    at aggregate.reduce (/usr/local/share/.config/yarn/global/node_modules/@antora/content-classifier/lib/classify-content.js:26:11)
    at Array.reduce (<anonymous>)
    at classifyContent (/usr/local/share/.config/yarn/global/node_modules/@antora/content-classifier/lib/classify-content.js:22:36)
    at Promise.all.aggregateContent.then (/usr/local/share/.config/yarn/global/node_modules/@antora/site-generator-default/lib/generate-site.js:19:59)
```

**Comment by shumonsharif** [comment]
Fixed this issue with commit https://github.com/quarkiverse/quarkus-cxf/commit/95b16734ad9fc176c27ed561e814bfd6550aad63

@gastaldi To prevent this issue from reoccurring, I'm goin to avoid the `v*` wildcard all together.  It makes much more sense to be explicit about which branches we'd like docs for, and that would mitigate this issue to some degree.

@dufoli I think this may be a good time to clean up our branches and maybe just leave HEAD and v0.9 for docs generation - do you think we need any other branches for docs?

```yaml
    - url: https://github.com/quarkiverse/quarkus-cxf.git
      branches: [HEAD, v0.9]
      start_path: docs
```
