### ISSUE TITLE
Runtime initialization for org.apache.cxf.attachment.ImageDataContentHandler

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-cxf#305]
After upgrading to `2.4.0/0.10.0` I had to add: `--initialize-at-run-time=org.apache.cxf.attachment.ImageDataContentHandler` for the application to work in native.
If not, some exceptions are thrown at native build time related to `java.awt` classes.

For instance with `--trace-class-initialization=java.awt.Image`, the build fails with:

```
Error: Classes that should be initialized at run time got initialized during image building:
 sun.awt.AppContext the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.AppContext got initialized use --trace-class-initialization=sun.awt.AppContext
java.awt.EventQueue the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.EventQueue got initialized use --trace-class-initialization=java.awt.EventQueue
java.awt.Toolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
java.awt.Image the class was requested to be initialized at run time (Quarkus run time init for AWT). org.apache.cxf.attachment.ImageDataContentHandler caused initialization of this class with the following trace:
        at java.awt.Image.<clinit>(Image.java:53)
        at java.lang.Class.forName0(Unknown Source)
        at java.lang.Class.forName(Class.java:398)
        at java.awt.datatransfer.DataFlavor.tryToLoadClass(DataFlavor.java:139)
        at java.awt.datatransfer.DataFlavor.initialize(DataFlavor.java:529)
        at java.awt.datatransfer.DataFlavor.<init>(DataFlavor.java:430)
        at java.awt.datatransfer.DataFlavor.createConstant(DataFlavor.java:175)
        at java.awt.datatransfer.DataFlavor.<clinit>(DataFlavor.java:212)
        at org.apache.cxf.attachment.ImageDataContentHandler.<clinit>(ImageDataContentHandler.java:55)

```

**Comment by darkeagle1337** [comment]
When can we expect the next release?

**Comment by shumonsharif** [comment]
I believe we're due for one, will try to get it out this weekend.

**Comment by shumonsharif** [comment]
Closing this issue, release 0.11.0 will be out shortly.
