### ISSUE TITLE
Grpc problem invoke @RequestScoped bean in vertx.executeBlocking

### ISSUE THREAD

**Issue by AndreyChukhlebov** [quarkiverse/quarkus-cxf#318]
Problem when trying to implement a blocking ServerInterceptor.
` @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call,
                                                                 Metadata headers,
                                                                 ServerCallHandler<ReqT, RespT> next) {
        
        vertx.executeBlocking(new Handler<Promise<Object>>() {
            @Override
            public void handle(Promise<Object> f) {
                ServerCall.Listener<ReqT> listener = next.startCall(call, headers);
                f.complete(null);
            }
        }, false, null);

        return ...;
    }`

in the next ServerInterceptor invoke @RequestScoped bean 

result `(vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
	at ru.sbrf.cache.service.impl.Context_ProducerMethod_suplier_b43aa8219c09ed89693f4b98bed0aacd817a61df_ClientProxy.arc$delegate(Context_ProducerMethod_suplier_b43aa8219c09ed89693f4b98bed0aacd817a61df_ClientProxy.zig:60)
	at ru.sbrf.cache.service.impl.Context_ProducerMethod_suplier_b43aa8219c09ed89693f4b98bed0aacd817a61df_ClientProxy.get(Context_ProducerMethod_suplier_b43aa8219c09ed89693f4b98bed0aacd817a61df_ClientProxy.zig:135)
	at ru.sbrf.cache.service.impl.Imitation.TestInterceptor.interceptCall(TestInterceptor.java:37)
	at ru.sbrf.cache.service.impl.Context_ProducerMethod_blockingServerInterceptorImitation_0537643601c5f447772e619749e3f5a02566626c_ClientProxy.interceptCall(Context_ProducerMethod_blockingServerInterceptorImitation_0537643601c5f447772e619749e3f5a02566626c_ClientProxy.zig:183)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at ru.sbrf.cache.service.impl.Imitation.BlockingServerInterceptorMod$1.handle(BlockingServerInterceptorMod.java:39)
	at ru.sbrf.cache.service.impl.Imitation.BlockingServerInterceptorMod$1.handle(BlockingServerInterceptorMod.java:36)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by shumonsharif** [comment]
@AndreyChukhlebov Is this an issue with the CXF extension?  On initial glance, I don't see how it's tied to this extension?

**Comment by AndreyChukhlebov** [comment]
https://github.com/AndreyChukhlebov/cache 
here you can reproduce
The problem is @RequestScoped creates context in GrpcRequestContextGrpcInterceptor
    and is stored in RequestContext.currentContext and it is ThreadLocal, so the initialized beans are not visible further on the blocking thread.

    The solutions I see
            1) @Blocking blocks everything from GrpcRequestContextGrpcInterceptor
            2) Give the ability to change the priority of GrpcRequestContextGrpcInterceptor

**Comment by AndreyChukhlebov** [comment]
https://github.com/AndreyChukhlebov/cache 
here you can reproduce
The problem is @RequestScoped creates context in GrpcRequestContextGrpcInterceptor
    and is stored in RequestContext.currentContext and it is ThreadLocal, so the initialized beans are not visible further on the blocking thread.

    The solutions I see
            1) @Blocking blocks everything from GrpcRequestContextGrpcInterceptor
            2) Give the ability to change the priority of GrpcRequestContextGrpcInterceptor

**Comment by shumonsharif** [comment]
@AndreyChukhlebov Your issue does not appear to be relevant to this extension in any way.  I also don't see any reference to this extension in the git repo you shared.  May I suggest you open an issue in the main Quarkus project?
