### ISSUE TITLE
'No Java extensionType found' error when running as an package jar

### ISSUE THREAD

**Issue by renanwillian** [quarkiverse/quarkus-cxf#332]
I have a application that is running OK in Quarkus Dev mode but fails as an package jar.

I've got the following error when running the jar:
```
javax.wsdl.WSDLException: WSDLException: faultCode=CONFIGURATION_ERROR: No Java extensionType found to represent a '{http://www.w3.org/2006/05/addressing/wsdl}UsingAddressing' element in the context of a 'javax.wsdl.Binding'.
        at javax.wsdl.extensions.ExtensionRegistry.createExtension(ExtensionRegistry.java:350)
        at org.apache.cxf.jaxws.support.JaxWsEndpointImpl.buildWsdlExtensibilities(JaxWsEndpointImpl.java:349)
        at org.apache.cxf.jaxws.support.JaxWsEndpointImpl.<init>(JaxWsEndpointImpl.java:211)
        at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.createEndpoint(JaxWsServiceFactoryBean.java:233)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:182)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:148)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:130)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy_0(QuarkusCxfProcessor$startRoute2108765474.zig:175)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy(QuarkusCxfProcessor$startRoute2108765474.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:763)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
```

I added the following config to provide additional logging details:
```
quarkus.log.level=INFO
quarkus.log.category."org.apache.cxf".level=TRACE
quarkus.log.category."io.quarkiverse.cxf".level=TRACE
```

Then I was getting the following errors when executing the generated jar:
```
2021-12-20 11:47:44,285 DEBUG [org.apa.cxf.bus.ext.Extension] (main) Could not load optional extension org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader.
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:233)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeansOfType(ExtensionManagerImpl.java:333)
        at org.apache.cxf.wsdl11.WSDLManagerImpl.setBus(WSDLManagerImpl.java:136)
        at java.base/jdk.internal.reflect.Nati:veMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.common.injection.ResourceInjector.invokeSetter(ResourceInjector.java:289)
        at org.apache.cxf.common.injection.ResourceInjector.visitMethod(ResourceInjector.java:237)
        at org.apache.cxf.common.annotation.AnnotationProcessor.processMethods(AnnotationProcessor.java:89)
        at org.apache.cxf.common.annotation.AnnotationProcessor.accept(AnnotationProcessor.java:72)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:123)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:117)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:227)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeanOfType(ExtensionManagerImpl.java:305)
        at org.apache.cxf.bus.extension.ExtensionManagerBus.getExtension(ExtensionManagerBus.java:181)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createSoapBinding(SoapBindingFactory.java:220)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createBindingInfo(SoapBindingFactory.java:208)
        at org.apache.cxf.binding.AbstractBindingFactory.createBindingInfo(AbstractBindingFactory.java:83)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:350)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.createBindingInfo(JaxWsServerFactoryBean.java:182)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpointInfo(AbstractWSDLBasedEndpointFactory.java:268)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:146)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:148)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:130)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy_0(QuarkusCxfProcessor$startRoute2108765474.zig:175)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy(QuarkusCxfProcessor$startRoute2108765474.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:785)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
Caused by: java.lang.RuntimeException: No ASM ClassWriterFound
        at org.apache.cxf.common.util.ASMHelperImpl.createClassWriter(ASMHelperImpl.java:207)
        at org.apache.cxf.wsdl.ExtensionClassGenerator.createExtensionClass(ExtensionClassGenerator.java:49)
        at org.apache.cxf.wsdl.ExtensionClassCreatorProxyService.createExtensionClass(ExtensionClassCreatorProxyService.java:37)
        at org.apache.cxf.wsdl.JAXBExtensionHelper.addExtensions(JAXBExtensionHelper.java:196)
        at org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader.createExtensor(XMLWSDLExtensionLoader.java:60)
        at org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader.registerExtensors(XMLWSDLExtensionLoader.java:48)
        at org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader.setupBus(XMLWSDLExtensionLoader.java:44)
        at org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader.<init>(XMLWSDLExtensionLoader.java:39)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:217)
        ... 42 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassWriter
        at org.apache.cxf.common.util.ASMHelperImpl.getASMClassWriterClass(ASMHelperImpl.java:83)
        at org.apache.cxf.common.util.ASMHelperImpl.getASMClass(ASMHelperImpl.java:99)
        at org.apache.cxf.common.util.ASMHelperImpl.createClassWriter(ASMHelperImpl.java:204)
        ... 54 more

2021-12-20 11:47:44,289 DEBUG [org.apa.cxf.bus.ext.Extension] (main) Could not load optional extension org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader.
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:233)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeansOfType(ExtensionManagerImpl.java:333)
        at org.apache.cxf.wsdl11.WSDLManagerImpl.setBus(WSDLManagerImpl.java:136)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.common.injection.ResourceInjector.invokeSetter(ResourceInjector.java:289)
        at org.apache.cxf.common.injection.ResourceInjector.visitMethod(ResourceInjector.java:237)
        at org.apache.cxf.common.annotation.AnnotationProcessor.processMethods(AnnotationProcessor.java:89)
        at org.apache.cxf.common.annotation.AnnotationProcessor.accept(AnnotationProcessor.java:72)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:123)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:117)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:227)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeanOfType(ExtensionManagerImpl.java:305)
        at org.apache.cxf.bus.extension.ExtensionManagerBus.getExtension(ExtensionManagerBus.java:181)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createSoapBinding(SoapBindingFactory.java:220)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createBindingInfo(SoapBindingFactory.java:208)
        at org.apache.cxf.binding.AbstractBindingFactory.createBindingInfo(AbstractBindingFactory.java:83)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:350)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.createBindingInfo(JaxWsServerFactoryBean.java:182)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpointInfo(AbstractWSDLBasedEndpointFactory.java:268)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:146)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:148)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:130)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy_0(QuarkusCxfProcessor$startRoute2108765474.zig:175)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy(QuarkusCxfProcessor$startRoute2108765474.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:785)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
Caused by: java.lang.NullPointerException
        at org.apache.cxf.wsdl.ExtensionClassGenerator.createExtensionClass(ExtensionClassGenerator.java:54)
        at org.apache.cxf.wsdl.ExtensionClassCreatorProxyService.createExtensionClass(ExtensionClassCreatorProxyService.java:37)
        at org.apache.cxf.wsdl.JAXBExtensionHelper.addExtensions(JAXBExtensionHelper.java:196)
        at org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader.createExtensor(AddressingWSDLExtensionLoader.java:49)
        at org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader.<init>(AddressingWSDLExtensionLoader.java:42)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:217)
        ... 42 more

2021-12-20 11:47:44,293 DEBUG [org.apa.cxf.bus.ext.Extension] (main) Could not load optional extension org.apache.cxf.transport.http.HTTPWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.transport.http.HTTPWSDLExtensionLoader.
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:233)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeansOfType(ExtensionManagerImpl.java:333)
        at org.apache.cxf.wsdl11.WSDLManagerImpl.setBus(WSDLManagerImpl.java:136)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.common.injection.ResourceInjector.invokeSetter(ResourceInjector.java:289)
        at org.apache.cxf.common.injection.ResourceInjector.visitMethod(ResourceInjector.java:237)
        at org.apache.cxf.common.annotation.AnnotationProcessor.processMethods(AnnotationProcessor.java:89)
        at org.apache.cxf.common.annotation.AnnotationProcessor.accept(AnnotationProcessor.java:72)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:123)
        at org.apache.cxf.common.injection.ResourceInjector.inject(ResourceInjector.java:117)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:227)
        at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeanOfType(ExtensionManagerImpl.java:305)
        at org.apache.cxf.bus.extension.ExtensionManagerBus.getExtension(ExtensionManagerBus.java:181)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createSoapBinding(SoapBindingFactory.java:220)
        at org.apache.cxf.binding.soap.SoapBindingFactory.createBindingInfo(SoapBindingFactory.java:208)
        at org.apache.cxf.binding.AbstractBindingFactory.createBindingInfo(AbstractBindingFactory.java:83)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:350)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.createBindingInfo(JaxWsServerFactoryBean.java:182)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpointInfo(AbstractWSDLBasedEndpointFactory.java:268)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:146)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:148)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:130)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy_0(QuarkusCxfProcessor$startRoute2108765474.zig:175)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute2108765474.deploy(QuarkusCxfProcessor$startRoute2108765474.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:785)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
Caused by: java.lang.NullPointerException
        at org.apache.cxf.wsdl.ExtensionClassGenerator.createExtensionClass(ExtensionClassGenerator.java:54)
        at org.apache.cxf.wsdl.ExtensionClassCreatorProxyService.createExtensionClass(ExtensionClassCreatorProxyService.java:37)
        at org.apache.cxf.wsdl.JAXBExtensionHelper.addExtensions(JAXBExtensionHelper.java:196)
        at org.apache.cxf.transport.http.HTTPWSDLExtensionLoader.createExtensor(HTTPWSDLExtensionLoader.java:51)
        at org.apache.cxf.transport.http.HTTPWSDLExtensionLoader.<init>(HTTPWSDLExtensionLoader.java:40)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.cxf.bus.extension.Extension.load(Extension.java:217)
        ... 42 more
```

It seams like the classes are missing from JAXBContext, how can I fix it?
It could be related to #238.

**Comment by shumonsharif** [comment]
Hi @renanwillian Thanks for the issue; from an initial glance, the DEBUG level statements can safely be ignored.  Wanted to confirm a few things:
- Is your package application running, or does it terminate when you get the exception?
- Are you using WS Addressing, and are the relevant libraries in the classpath?
- Are you able to create and attach a reproducer?

**Comment by renanwillian** [comment]
Hi @shumonsharif Thanks for the reply

> Is your package application running, or does it terminate when you get the exception?

The application keeps running after the exception, I can still send soap requests but with blank response (http 202).

> Are you using WS Addressing, and are the relevant libraries in the classpath?

Yes, and that was the problem after all, adding the following dependency solve the issue:
```
<dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-ws-addr</artifactId>
      <version>${apache.cxf.version}</version>
</dependency>
```

The thing that still bugs my mind is that was running fine in dev mode, shouldn't dev mode have the same issue?

**Comment by shumonsharif** [comment]
> The thing that still bugs my mind is that was running fine in dev mode, shouldn't dev mode have the same issue?

You are correct, dev mode should have had the same issue.  Given the addition of the `cxf-rt-ws-addr` dependency resolved the issue, it may have been some sort of local misconfiguration all along - hard to tell.

Please feel free to reopen in case you are able to put together a reproducer.
