### ISSUE TITLE
@RequestScoped Webservice not working properly

### ISSUE THREAD

**Issue by Aviss** [quarkiverse/quarkus-cxf#373]
I'm trying to inject a `@RequestScoped` Bean into my Webservice. 
However trying to invoke any method in `someService` produces a `ContextNotActiveException`
Making the Webservice itself `@RequestScoped` instead produces a `ContextNotActiveException` as soon as the WebMethod is called.
```
@WebService(endpointInterface = "com.example.IntfJobsPushPortType")
@RequestScoped
public class SoapExampleEndpoint implements IntfJobsPushPortType {
  @Resource WebServiceContext context;
  @Inject MyRequestScopedBean someService;

  @Override
  public void sendIntfJobsExport(SomeResponse response) {
    [...]
  }
}
```
I found [this issue](https://github.com/quarkiverse/quarkus-cxf/issues/106) which states essentially the same problem, which appears to be resolved. 
Is there any additional configuration that needs to be done in order to use `@RequestScoped`? I have nothing beyond this Java-Class and the auto-generated Interface it implements. 

```
@WebService(name = "IntfJobsPushPortType", targetNamespace = "http://intf.example.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntfJobsPushPortType {
    @WebMethod(action = "http://www.example.com/[...]/IntfJobsSendExport")
    @Oneway
    public void sendIntfJobsExport(
        @WebParam(name = "someResponse", targetNamespace = "http://intf.example.com/", partName = "response")
        SomeResponse response);

}
```

For completness' sake here is the stacktrace I'm getting:
```
2022-03-11 10:36:55,351 WARN  [org.apa.cxf.pha.PhaseInterceptorChain] (default-workqueue-1) Application {http://example.com/}SoapExampleEndpoint_ClientProxyService#{http://intf.example.com/}sendIntfJobsExport has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.createFault(AbstractJAXWSMethodInvoker.java:267)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:232)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:85)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:74)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$2.run(ServiceInvokerInterceptor.java:126)
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:131)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.phase.PhaseInterceptorChain.resume(PhaseInterceptorChain.java:277)
	at org.apache.cxf.interceptor.OneWayProcessorInterceptor$1.run(OneWayProcessorInterceptor.java:139)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:413)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:346)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:46)
	at com.example.SoapExampleEndpoint_ClientProxy.arc$delegate(Unknown Source)
	at com.example.SoapExampleEndpoint_ClientProxy.sendIntfJobsExport(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.performInvocation(JAXWSMethodInvoker.java:66)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	... 17 more
```

**Comment by shumonsharif** [comment]
Hi @Aviss There shouldn't be any additional configurations required.  Everything appears to work fine using the setup below.  Please attach a reproducer if you need help, could be something unique to your configuration?

```java
@WebService
public interface GreetingSoap {

    @WebMethod 
    public String sayHello(@WebParam(name = "name") String name);

}
```

```java
@RequestScoped
public class GreetingService {

    public String greeting(String name) { return "hello " + name; }

}
```

```java
@WebService(endpointInterface = "org.acme.getting.started.GreetingSoap")
@RequestScoped
public class GreetingSoapResource implements GreetingSoap {

    @Inject GreetingService service;

    @Override
    public String sayHello(String name) { return service.greeting(name); }
}
```

**Comment by shumonsharif** [comment]
I think I managed to recreate the issue, it's likely being caused by the use of the `@Oneway` annotation.  Will try to dig in further and keep you posted.

**Comment by shumonsharif** [comment]
@Aviss  There basically appears to be a clash between CXF's `@Oneway` behavior and the `@RequestScoped` functionality.  I don't believe there's a clean way to address this in the extension, but I believe something like the workaround below should address any issues you are seeing, can you please confirm?

```java
import io.quarkus.runtime.StartupEvent;
import org.apache.cxf.Bus;
import org.apache.cxf.BusFactory;
import org.apache.cxf.interceptor.OneWayProcessorInterceptor;
import org.jboss.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class CxfBusConfigurer {

    Logger logger = Logger.getLogger(CxfBusConfigurer.class);

    void onStart(@Observes StartupEvent ev) {
        logger.info("Configuring OneWayProcessorInterceptor");
        final Bus bus = BusFactory.getThreadDefaultBus();
        bus.setProperty(OneWayProcessorInterceptor.USE_ORIGINAL_THREAD, true);
    }

}
```

**Comment by Aviss** [comment]
Thanks for the quick help!

I can confirm that the above class solves the `@RequestScoped` issue. However, the `WebServiceContext` injected via `@Resource` is now `null`

**Comment by shumonsharif** [comment]
You seem to be implying that `WebServiceContext` was not null before this change, is that correct?  I'll really need a reproducer to help you out if that's the case.  What I'm guessing is that `WebServiceContext` was always null.

**Comment by shumonsharif** [comment]
So digging in on my end, I don't see how `WebServiceContext` could be anything but null, regardless of the `@RequestScoped` issue.  In any case, the `WebServiceContext` contains references to the `Principal` and `MessageContext` - I'm guessing you are trying to access either.

For the `Principal` instance contained within the `WebServiceContext`, your best bet is to use the below instead:

```java
    @Inject
    SecurityIdentity si;

    public void test() {
        logger.info("userPrincipal:" + si.getPrincipal().getName());
    }

```

For the `MessageContext` within `WebServiceContext` you can instead use something like the below:

```java
    Message currentMessage = PhaseInterceptorChain.getCurrentMessage();
```

**Comment by Aviss** [comment]
That is interesting. I had that code running without problems for quite a while, doing Basic Auth via the `MessageContext`
The `WebServiceContext` got injected properly when the WebService was "scopeless", as in, no scope-annotation was used. 

I now wanted to inject a `@RequestScoped` Bean into the WebService which, as I understand it, does not work without adding a appropriate scope-annotation to the service.
I can not verify if the `WebServiceContext` is `null` without adding the BusConfigurer, as I get a `ContextNotActiveException` before any of the `@WebMethod` code can be executed.

The only difference that I can think of is, that prior to working on this, that `SoapExampleEndpoint` was not annotated with `@WebService`. I took that change from #106, after i got 404s when trying to access the Endpoint when it was annotated with `@RequestScoped` but without any annotations it worked fine.

I probably won't have any time to get to your suggestions until Monday, but will report back, when I do. Getting a hold of the `MessageContext` in a different way sounds promising.
I can then also try to make a reproducer but that could involve some work as I would need to sanitize the WSDL-file

**Comment by shumonsharif** [comment]
Sounds good, thanks @Aviss please keep us posted!

**Comment by Aviss** [comment]
I was able to access BasicAuth through `PhaseInterceptorChain.getCurrentMessage().get(AuthorizationPolicy.class);` 

However, after trying around some more, it turns out the `@RequestScoped` annotation seems to be redundant if the `CxfBusConfigurer` is used. More interestingly, omitting the `@RequestScoped` annotation allows the `WebServiceContext` to be injected properly again, while also being able to access other `@RequestScoped` beans.

The only thing that does not work at the moment is reproducing the behaviour in a `@QuarkusTest`. Though that seems to be caused by Quarkus not invoking `StartupEvent`s at all during tests. I'm not sure why that happens but it is highly unlikely to be related to this extension. 

Thanks again for the help.

**Comment by shumonsharif** [comment]
Thanks @Aviss for your investigation and insights!

> More interestingly, omitting the `@RequestScoped` annotation allows the `WebServiceContext` to be injected properly again, while also being able to access other `@RequestScoped` beans.

I just tried injecting `WebServiceContext` without the `@RequestScoped` annotation and it is indeed getting injected properly.  This is good to know.

Are we good with closing this issue?

**Comment by Aviss** [comment]
Yes, my issue has been resolved.
