### ISSUE TITLE
Failed to load class :java.lang.ClassNotFoundException: org.apache.cxf.bindings.xformat.XMLBindingMessageFormatExtensibility

### ISSUE THREAD

**Issue by mayankchincholkar** [quarkiverse/quarkus-cxf#380]
Getting quite a few exceptions when invoking the SOAP client

1.  trying to read the schema file  Writing XML Schema for com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator@255e3a3[http://schema.cmo/SvcInfoModel=com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace@5928ca6,http://schema.cmo/AcctStmtInq=com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator$Namespace@454fad4c]: com.sun.xml.bind.v2.util.StackRecorder
        at com.sun.xml.bind.v2.schemagen.XmlSchemaGenerator.write(XmlSchemaGenerator.java:425)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.generateSchema(JAXBContextImpl.java:790)
        at org.apache.cxf.common.jaxb.JAXBUtils.generateJaxbSchemas(JAXBUtils.java:810)
        at org.apache.cxf.jaxb.JAXBDataBinding.generateJaxbSchemas(JAXBDataBinding.java:474)
        at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:391)

2.  Failed to load class :java.lang.ClassNotFoundException: org.apache.cxf.bindings.xformat.XMLBindingMessageFormatExtensibility
2022-03-17 15:14:11,264 DEBUG [org.apa.cxf.bus.ext.Extension] (executor-thread-0) Could not load optional extension org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object

3. Failed to load class :java.lang.ClassNotFoundException: org.apache.cxf.transports.http.configuration.HTTPClientPolicyExtensibility
2022-03-17 15:14:11,294 DEBUG [org.apa.cxf.bus.ext.Extension] (executor-thread-0) Could not load optional extension org.apache.cxf.transport.http.HTTPWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.transport.http.HTTPWSDLExtensionLoader.

4. Failed to load class :java.lang.ClassNotFoundException: org.apache.cxf.ws.addressing.wsdl.UsingAddressingExtensibility
2022-03-17 15:14:11,323 DEBUG [org.apa.cxf.bus.ext.Extension] (executor-thread-0) Could not load optional extension org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader: org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader.

The execution works fine and able to invoke the soap web service, however these exceptions are creating lot of noise in the logs.
Quarkus version 2.7.1.Final
quarkus-cxf version 0.13.1

**Comment by shumonsharif** [comment]
It looks like you have DEBUG logging enabled, so you _should_ be seeing these in your logs.

Have you tried turning down the log level?

**Comment by mayankchincholkar** [comment]
> 

Yep thats right

**Comment by shumonsharif** [comment]
OK, closing this issue as the logs are from CXF, and can easily be turned off by setting the appropriate log levels.
