### ISSUE TITLE
UnsatisfiedResolutionException

### ISSUE THREAD

**Issue by shumonsharif** [quarkiverse/quarkus-cxf#410]
### Discussed in https://github.com/quarkiverse/quarkus-cxf/discussions/408

<div type='discussions-op-text'>

<sup>Originally posted by **asanglard** April  5, 2022</sup>
Hello,

when I try to start my app, this error appears

java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.acme.MyService and qualifiers [@CXFClient(value = "MyService")]

Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.orange.holmes.cfx.com.acme.MyService and qualifiers [@CXFClient(value = "MyService")]
	- java member: MySoapClient#MyService
	- declared on CLASS bean [types=[java.lang.Object, MySoapClient], qualifiers=[@Default, @Any], target=MySoapClient]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:428)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:524)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:260)
	... 13 more

I have previously generated cfx source code with maven plugin.

Any idea to solve this problem ?</div>

**Comment by shumonsharif** [comment]
Some suggestions :

- I don't know if the error generated in the log may be more explicit in case someone else make the same error. Like a missing WebService annotation on the service-interface specified...
- In the doc, maybe you can also explicit the SEI acronym (Service Endpoint Interface)
