### ISSUE TITLE
SEI injection not working if SEI was generated in a different module

### ISSUE THREAD

**Issue by STriX96** [quarkiverse/quarkus-cxf#432]
Hey!

Typically in our projects we generate java code from wsdl in a separate maven project and use it as a dependency in other modules of the project. The structure looks like this: 

- api-parent (parent maven)
-- api-definition (contains the generated classes from wsdl)
-- api-service (using api-definition as a dependency to implement methods)

I'm using quarkus-cxf 1.0.0

In this case when I injected the SEI as a CXFClient i got the following error (Changed actual package and class names for security reasons):

```[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.8.2.Final:build (default) on project dokos-api-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.SoapPortType and qualifiers [@CXFClient(value = "api-client")]
[ERROR] 	- java member: com.example.SoapClient#SoapPortType
[ERROR] 	- declared on CLASS bean [types=[com.example.SoapClient, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.SoapClient]
[ERROR] 	The following beans match by type, but none have matching qualifiers:
[ERROR] 		- Bean [class=com.example.SoapPortTypeImpl, qualifiers=[@Default, @Any]]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1209)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:134)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:494)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.SoapPortType and qualifiers [@CXFClient(value = "api-client")]
[ERROR] 	- java member: com.example.SoapClient#SoapPortType
[ERROR] 	- declared on CLASS bean [types=[com.example.SoapClient, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.SoapClient]
[ERROR] 	The following beans match by type, but none have matching qualifiers:
[ERROR] 		- Bean [class=com.example.SoapPortTypeImpl, qualifiers=[@Default, @Any]]
[ERROR] 	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:411)
[ERROR] 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:527)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:263)
[ERROR] 	... 13 more
```

SEI: 

```java
@WebService(targetNamespace = "example", name = "SoapPortType")
@XmlSeeAlso({ObjectFactory.class, com.example.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SoapPortType {
   //@WebMethod ...
}
```

SoapPortTypeImpl class: 

```java
@WebService(endpointInterface = "com.example.SoapPortType", serviceName = "SoapPortType")
public class SoapPortTypeImpl implements SoapPortType {
   //implemented methods
}
```

SoapClient class:

```java
@ApplicationScoped
public class SoapClient {
    @Inject
    @CXFClient("api-client")
    SoapPortType soapPortType;
}
```

my application.properties: 

```java.properties
quarkus.cxf.path=/ws
quarkus.cxf.endpoint."/api".implementor=com.example.SoapPortTypeImpl
quarkus.cxf.client."api-client".service-interface=com.example.SoapPortType
quarkus.cxf.client."api-client".client-endpoint-url=http://localhost:8090/api
```

Later as I had no clue what's the problem, I generated Java code from the wsdl in the api-service module directly and without changing anything else it started working well.

Can you please help me what can be the problem?

**Comment by STriX96** [comment]
Aynone bumping into this, I managed to make it work by adding this plugin to the api-definition pom.xml: 

```
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>1.2.2</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
