### ISSUE TITLE
Can't use XSLT feature in native mode

### ISSUE THREAD

**Issue by Ballsigno** [quarkiverse/quarkus-cxf#501]
Hi. I have a question about [XSLT feature](https://cxf.apache.org/docs/xslt-feature.html).

```java
// get my client
Client client = ClientProxy.getClient(myService);

// create XSLT InInterceptor (from ~/resources/test.xsl)
XSLTInInterceptor inInterceptor = new XSLTInInterceptor(Phase.RECEIVE, null, null, "test.xsl");

// add to my client settings
client.getInInterceptors().add(inInterceptor);
```

↑ It works fine in dev mode, but when I tried in native mode,  it was failed.

```
java.lang.IllegalArgumentException: Cannot create XSLT template from path: test.xsl
        at org.apache.cxf.feature.transform.AbstractXSLTInterceptor.<init>(AbstractXSLTInterceptor.java:74)
        at org.apache.cxf.feature.transform.XSLTInInterceptor.<init>(XSLTInInterceptor.java:51)
        at jp.co.kyocera.espf.aems.module.external_if.library.jepx.client.JepxSpotClient.init(JepxSpotClient.java:122)
        at jp.co.kyocera.espf.aems.module.external_if.library.jepx.client.JepxSpotClient_ClientProxy.init(Unknown Source)
        at jp.co.kyocera.espf.aems.module.external_if.library.jepx.JepxClient.init(JepxClient.java:68)
        at jp.co.kyocera.espf.aems.module.external_if.library.jepx.JepxClient_ClientProxy.init(Unknown Source)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.service.SpotMarketPlanSubmissionService.prepareSpotBid(SpotMarketPlanSubmissionService.java:130)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.service.SpotMarketPlanSubmissionService.submitPlan(SpotMarketPlanSubmissionService.java:70)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.service.SpotMarketPlanSubmissionService_ClientProxy.submitPlan(Unknown Source)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.controller.JepxController.submitSpotMarketPlan(JepxController.java:37)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.controller.JepxController_Subclass.submitSpotMarketPlan$$superforward1(Unknown Source)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.controller.JepxController_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.controller.JepxController_Subclass.submitSpotMarketPlan(Unknown Source)
        at jp.co.kyocera.espf.aems.module.external_if.jepx.controller.JepxController$quarkusrestinvoker$submitSpotMarketPlan_9d4fc50d33a38a22f52809563962a4ceb6a41726.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: javax.xml.transform.TransformerConfigurationException: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1077)
        at org.apache.cxf.feature.transform.AbstractXSLTInterceptor.<init>(AbstractXSLTInterceptor.java:71)
        ... 35 more
Caused by: java.lang.NullPointerException
        at com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.getFileName(ErrorMsg.java:264)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.<init>(ErrorMsg.java:237)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.makeInstance(Parser.java:1000)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.startElement(Parser.java:1312)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:269)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:192)
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:130)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:439)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:478)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:572)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1036)
        ... 36 more
```

If the xsl file doesn't exist, I'm sure I will get 'Cannot load XSLT from path:" error.
Therefore I passed the right argument but failed.
Is this a bug or am I missing something?

**Comment by shumonsharif** [comment]
Hi @Ballsigno Did you include the test.xsl resource in your native image?
https://quarkus.io/guides/writing-native-applications-tips#including-resources

**Comment by Ballsigno** [comment]
@shumonsharif  
Thank you for your reply!  
Yes, I have pom.xml that has include setting.

```xml
<profile>
~ omit ~
  <properties>
    <skipITs>false</skipITs>
    <quarkus.package.type>native</quarkus.package.type>
    <quarkus.native.additional-build-args>-H:IncludeResources=test.xsl</quarkus.native.additional-build-args>
  </properties>
```

Additionally, I have tried this in native mode, and I successfully got the input stream.
(But somehow, XSLTInInterceptor doesn't work.)

```
InputStream testStream = ClassLoaderUtils.getResourceAsStream("test.xsl", this.getClass());
Log.info(testStream.available()); // has value
```

**Comment by shumonsharif** [comment]
Likely a bug; thanks for opening the issue!  Would you be able to provide a small reproducer?

**Comment by Ballsigno** [comment]
Alright, I created the small one.
I really want to know whether this will be fixed in a few days or not.
Let me know if you need anything.

https://github.com/Ballsigno/quarkus-cxf-xslt-test/tree/master/quarkus-cxf-xslt-test

**Comment by shumonsharif** [comment]
Thank you so much @Ballsigno !  This helps tremendously.

Unfortunately, debugging native issues always takes quite a bit of time.  Not sure at this stage if this will be a quick thing or not, though I'm doubtful it'll be fixed and released in a few days.  Will certainly prioritize this issue for you, and will keep you posted on progress.

**Comment by Ballsigno** [comment]
@shumonsharif
Thank you for your support! It's understandable.
I'm researching whether I can use this for my purpose these days, and now I can see the silver lining. If it turned out to be complicated, I will wait patiently🙏

**Comment by ppalaga** [comment]
Making XSLT work in native mode is indeed tricky. Camel Quarkus supports it via its `camel-quarkus-xslt` extension. It is tested there only in Camel related scenarios, but I think it might work for you as well. What I think you should do is the following:

1. Go to https://code.quarkus.io/?e=org.apache.camel.quarkus%3Acamel-quarkus-xslt&extension-search=origin:platform%20camel-quarkus-xslt 
2. Generate the project zip, unpack locally, take the properties, dependencyManagement and dependencies from there and add them into your project.
3. Make sure that Quarkus version from code.quarkus.io is compatible with `quarkus-cxf` version you use. If you wait a week or so, the versions that should work well with each other are Quarkus 2.12.0.Final, Camel Quarkus 2.12.0 (managed in Quarkus Platform BOM 2.12.0.Final, so you actually do not need to care for the Camel Quarkus version) and quarkus-cxf 1.15.0
Starting with 1.15.0, Quarkus CXF will also have a BOM `io.quarkiverse.cxf:quarkus-cxf-bom` that you should import into your project
4. Configure `quarkus.camel.xslt.sources` in your `application.properties` - see https://camel.apache.org/camel-quarkus/2.11.x/reference/extensions/xslt.html
5. Report whether it worked for you

**Comment by Ballsigno** [comment]
Thanks for clear steps instructions🙇🏻‍♂️
I’m not familiar with those things. Therefore I’m not so sure how is that related to my problem. Anyway, I'll give it a try tomorrow or the day after tomorrow.

**Comment by ppalaga** [comment]
> not so sure how is that related to my problem

To make Java code work in native mode, you need to provide some (sometimes a lot of) GraalVM configuration. That's what Quarkus extensions do (among other things). camel-quarkus-xslt does it for XSLT.

**Comment by Ballsigno** [comment]
Thank you for your explanation.
I tried it Java 11 and 17, but very unfortunately, It didn't work for me.
(I created [a branch](https://github.com/Ballsigno/quarkus-cxf-xslt-test/tree/feature/ADD_APACHE_CAMEL_XSLT/quarkus-cxf-xslt-test) based on the reproducer)

Indeed it seems it affects XSLT feature because the error message is change. (But my xsl file is valid format.)

```
java.lang.IllegalArgumentException: Cannot create XSLT template from path: test.xsl
        at org.apache.cxf.feature.transform.AbstractXSLTInterceptor.<init>(AbstractXSLTInterceptor.java:74)
        at org.apache.cxf.feature.transform.XSLTInInterceptor.<init>(XSLTInInterceptor.java:51)
        at org.acme.GreetingResource.test1(GreetingResource.java:47)
        at org.acme.GreetingResource$quarkusrestinvoker$test1_7ef637907f0bfe03310c5187ae0e45fdc512a9ab.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: javax.xml.transform.TransformerConfigurationException: Could not compile stylesheet
        at org.apache.xalan.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:832)
        at org.apache.camel.quarkus.support.xalan.XalanTransformerFactory.newTemplates(XalanTransformerFactory.java:70)
        at org.apache.cxf.feature.transform.AbstractXSLTInterceptor.<init>(AbstractXSLTInterceptor.java:71)
        ... 15 more

```

**Comment by Ballsigno** [comment]
This may mislead you, but If I do this in my GreetingResource.java (with apache camel), an error message is like this.

```java
byte[][] bytecodes = xsltc.compile(null, input, 2);
```
↓
```
java.lang.NoClassDefFoundError: org.apache.xalan.xsltc.compiler.ObjectFactory
        at org.apache.xalan.xsltc.compiler.ObjectFactory.class$(ObjectFactory.java:292)
        at org.apache.xalan.xsltc.compiler.ObjectFactory.findClassLoader(ObjectFactory.java:410)
        at org.apache.xalan.xsltc.compiler.Parser.makeInstance(Parser.java:925)
        at org.apache.xalan.xsltc.compiler.Parser.startElement(Parser.java:1250)
        at org.apache.xalan.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:285)
        at org.apache.xalan.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:212)
        at org.apache.xalan.xsltc.trax.DOM2SAX.parse(DOM2SAX.java:149)
        at org.apache.xalan.xsltc.compiler.Parser.parse(Parser.java:421)
        at org.apache.xalan.xsltc.compiler.XSLTC.compile(XSLTC.java:347)
        at org.apache.xalan.xsltc.compiler.XSLTC.compile(XSLTC.java:446)
        at org.acme.GreetingResource.test2(GreetingResource.java:114)
        at org.acme.GreetingResource$quarkusrestinvoker$test2_d2274ff3c79dc2e39e2edcf2ae711ceac7eae414.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
java.lang.NullPointerException
        at org.acme.GreetingResource.test2(GreetingResource.java:116)
        at org.acme.GreetingResource$quarkusrestinvoker$test2_d2274ff3c79dc2e39e2edcf2ae711ceac7eae414.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by Ballsigno** [comment]
Hmm. I'm totally stuck on this.
 
Apache Camel seems create a factory and compile a xsl file in initialization process, and XsltBuilder retains the result(template). On the other hand, CXF does similar things after the application launch.(When I create XSLTInInterceptor.)  I don't know why it doesn't work though.
Since there is AbstractPhaseInterceptor, I can create own XSLTinterceptor, but I could not take the template which is created by Apache Camel.

Is there any other way to fix this? I would really appreciate any information.

**Comment by Ballsigno** [comment]
Finally, I found a workaround! Thank you @ppalaga, I wouldn't have found this approach by myself.
I don't know what's going on but, using quarkus camel resources work.
I created own interceptor, and avoid a default action that caused the problem.

Instated of doing this...
```java
// AbstractXSLTInterceptor.java
try {
    InputStream xsltStream = ClassLoaderUtils.getResourceAsStream(xsltPath, this.getClass());
    if (xsltStream == null) {
        throw new IllegalArgumentException("Cannot load XSLT from path: " + xsltPath);
    }
    Document doc = StaxUtils.read(xsltStream);
    TransformerFactory transformerFactory = TransformerFactory.newInstance();
    try {
        transformerFactory.setFeature(javax.xml.XMLConstants.FEATURE_SECURE_PROCESSING, true);
    } catch (javax.xml.transform.TransformerConfigurationException ex) {
      //
    }
    xsltTemplate = transformerFactory.newTemplates(new DOMSource(doc)); // Somehow failed!!
} catch (TransformerConfigurationException | XMLStreamException e) {
    throw new IllegalArgumentException(
        String.format("Cannot create XSLT template from path: %s", xsltPath), e);
}
```
↓
```java
// Inject and pass component as argument from caller.
@Inject
XsltComponent xslt;

// CustomInterceptor
try (XsltEndpoint endPoint = (XsltEndpoint) xslt.createEndpoint("xslt://" + xsltPath)) {
    endPoint.init();
    xsltTemplate = endPoint.getXslt().getTemplate();
} catch (Exception e) {
    throw new IllegalArgumentException(
        String.format("Cannot create XSLT template from path: %s", xsltPath), e);
}
```

@shumonsharif
I think I'll close this issue for now. is it okay? (I assume this is low priority...)
(I'll be happy if the XSLT feature is officially supported though.)

**Comment by ppalaga** [comment]
> I think I'll close this issue for now.

I'd vote for keeping this issue open, as it still does not work flawlessly. This issue also contains a lot of useful information.

I think our general aim should be to have a general purpose Quarkus XSLT extension that could be leveraged for both Camel and CXF use cases. I need to speak with Quarkus team whether they'd be ready to host it within quarkusio/quarkus repo.

**Comment by dufoli** [comment]
According error it mean that we need a ReflectiveClassBuildItem for class org.apache.xalan.xsltc.compiler.ObjectFactory
