### ISSUE TITLE
Unmarshalling Error: unexpected element when invoking a service with multiple parameters without explicit wrapper

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#582]
There is a disabled test reproducing this issue:

https://github.com/quarkiverse/quarkus-cxf/blob/226d033ffdde3785a3383bd6b565992d12e69711/integration-tests/mtom-awt/src/test/java/io/quarkiverse/cxf/it/ws/mtom/awt/server/MtomAwtTest.java#L27-L31

The stack trace: 

```
[INFO] Running io.quarkiverse.cxf.it.ws.mtom.awt.server.MtomAwtTest
[INFO] [stdout] 2022-10-28 17:44:40,183 INFO  [io.qua.cxf.dep.CxfEndpointImplementationProcessor] (build-16) Mapping a Vert.x handler for CXF to /soap/* as requested by [io.quarkiverse.cxf.it.ws.mtom.awt.server.ImageServiceImpl]
[INFO] [stdout] 2022-10-28 17:44:41,088 INFO  [org.apa.cxf.end.ServerImpl] (main) Setting the server's publish address to be /mtom-aws
[INFO] [stdout] 2022-10-28 17:44:41,095 INFO  [io.qua.cxf.tra.CxfHandler] (main) Web Service io.quarkiverse.cxf.it.ws.mtom.awt.server.ImageServiceImpl on /soap available.
[INFO] [stdout] 2022-10-28 17:44:41,225 INFO  [io.quarkus] (main) quarkus-cxf-integration-test-mtom-awt 1.6.0-SNAPSHOT on JVM (powered by Quarkus 2.13.3.Final) started in 2.874s. Listening on: http://localhost:8081
[INFO] [stdout] 2022-10-28 17:44:41,226 INFO  [io.quarkus] (main) Profile test activated. 
[INFO] [stdout] 2022-10-28 17:44:41,226 INFO  [io.quarkus] (main) Installed features: [awt, cdi, cxf, cxf-rt-features-logging, resteasy, smallrye-context-propagation, vertx]
[INFO] [stdout] 2022-10-28 17:44:42,710 INFO  [org.apa.cxf.ser.Ima.REQ_IN] (executor-thread-1) REQ_IN
[INFO] [stdout]     Address: http://localhost:8081/soap/mtom-aws/ImageService
[INFO] [stdout]     HttpMethod: POST
[INFO] [stdout]     Content-Type: multipart/related; type="application/xop+xml"; boundary="uuid:21ff4fef-e46f-491c-b425-c82060c7ce15"; start="<root.message@cxf.apache.org>"; start-info="text/xml"
[INFO] [stdout]     ExchangeId: 82d1da58-5c6e-4989-8044-e43468a1be10
[INFO] [stdout]     ServiceName: ImageService
[INFO] [stdout]     PortName: ImageServicePort
[INFO] [stdout]     PortTypeName: ImageService
[INFO] [stdout]     Headers: {SOAPAction="", transfer-encoding=chunked, Accept=*/*, Cache-Control=no-cache, User-Agent=Apache-CXF/3.5.3, connection=keep-alive, content-type=multipart/related; type="application/xop+xml"; boundary="uuid:21ff4fef-e46f-491c-b425-c82060c7ce15"; start="<root.message@cxf.apache.org>"; start-info="text/xml", Host=localhost:8081, Pragma=no-cache}
[INFO] [stdout]     Payload: 
[INFO] [stdout] --uuid:21ff4fef-e46f-491c-b425-c82060c7ce15
[INFO] [stdout] Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
[INFO] [stdout] Content-Transfer-Encoding: binary
[INFO] [stdout] Content-ID: <root.message@cxf.apache.org>
[INFO] [stdout] 
[INFO] [stdout] <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns1:uploadImage xmlns:ns1="https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt"><data xmlns="https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt"><xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href="cid:340b4daa-860e-40a5-afb3-cf82ad5de146-1@quarkiverse.github.io"/></data><name xmlns="https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt">linux-image-name</name></ns1:uploadImage></soap:Body></soap:Envelope>
[INFO] [stdout] --uuid:21ff4fef-e46f-491c-b425-c82060c7ce15
[INFO] [stdout] --- Content suppressed ---
[INFO] [stdout] ----uuid:21ff4fef-e46f-491c-b425-c82060c7ce15
[INFO] [stdout] 
[WARN] [stderr] org.apache.cxf.interceptor.Fault: Unmarshalling Error: unexpected element (uri:"https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt", local:"data"). Expected elements are (none) 
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:931)
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:737)
[WARN] [stderr]         at org.apache.cxf.jaxb.io.DataReaderImpl.read(DataReaderImpl.java:168)
[WARN] [stderr]         at org.apache.cxf.wsdl.interceptors.DocLiteralInInterceptor.getPara(DocLiteralInInterceptor.java:323)
[WARN] [stderr]         at org.apache.cxf.wsdl.interceptors.DocLiteralInInterceptor.handleMessage(DocLiteralInInterceptor.java:127)
[WARN] [stderr]         at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
[WARN] [stderr]         at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
[WARN] [stderr]         at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
[WARN] [stderr]         at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
[WARN] [stderr]         at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
[WARN] [stderr]         at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
[WARN] [stderr]         at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:271)
[WARN] [stderr]         at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:208)
[WARN] [stderr]         at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:45)
[WARN] [stderr]         at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
[WARN] [stderr]         at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
[WARN] [stderr]         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
[WARN] [stderr]         at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
[WARN] [stderr]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
[WARN] [stderr]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[WARN] [stderr]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[WARN] [stderr]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[WARN] [stderr]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[WARN] [stderr]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[WARN] [stderr]         at java.base/java.lang.Thread.run(Thread.java:834)
[WARN] [stderr] Caused by: javax.xml.bind.UnmarshalException
[WARN] [stderr]  - with linked exception:
[WARN] [stderr] [com.sun.istack.SAXParseException2; lineNumber: 0; columnNumber: 0; unexpected element (uri:"https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt", local:"data"). Expected elements are (none)]
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:453)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:387)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:356)
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder.doUnmarshal(JAXBEncoderDecoder.java:881)
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder.access$200(JAXBEncoderDecoder.java:103)
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder$3.run(JAXBEncoderDecoder.java:919)
[WARN] [stderr]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[WARN] [stderr]         at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:917)
[WARN] [stderr]         ... 24 more
[WARN] [stderr] Caused by: com.sun.istack.SAXParseException2; lineNumber: 0; columnNumber: 0; unexpected element (uri:"https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt", local:"data"). Expected elements are (none)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:713)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:227)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:94)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1118)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:543)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:525)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.MTOMDecorator.startElement(MTOMDecorator.java:81)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:45)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:216)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:150)
[WARN] [stderr]         at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:385)
[WARN] [stderr]         ... 30 more
[WARN] [stderr] Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom-awt", local:"data"). Expected elements are (none)
[WARN] [stderr]         ... 42 more
```

**Comment by ppalaga** [comment]
This should work. @ffang shows a test case on SpringBoot where it works https://github.com/apache/camel-quarkus/pull/4214#issuecomment-1294113013

**Comment by ppalaga** [comment]
Debugging QCXF and [this](https://github.com/ffang/camel-spring-boot-apache/commit/e43b1554dd9a38cbbe3465bf46e108596464994b) Camel Spring Boot's test by @ffang seems to suggest that we are missing some classes that are normally generated through ASM.

Let me try to revert this https://github.com/quarkiverse/quarkus-cxf/commit/83eb59cef12b76d870fb3cabcc1d3119a62c75f9 and see whether it helps.

**Comment by ppalaga** [comment]
> Debugging QCXF and [this](https://github.com/ffang/camel-spring-boot-apache/commit/e43b1554dd9a38cbbe3465bf46e108596464994b) Camel Spring Boot's test by @ffang seems to suggest that we are missing some classes that are normally generated through ASM.

This theory has proven wrong. All classes generated by ASM are there in the app. I thought, they were missing from wrapperClasses set that we hang on the service. https://github.com/quarkiverse/quarkus-cxf/pull/780 is an attempt in that direction, but it unfortunately introduces other issues. I am too new to JAXB to be able to tell what's wrong.

> Let me try to revert this [83eb59c](https://github.com/quarkiverse/quarkus-cxf/commit/83eb59cef12b76d870fb3cabcc1d3119a62c75f9) and see whether it helps.

This is a BS because this issue happens already in JVM mode.

**Comment by ppalaga** [comment]
BTW, the [Camel Spring Boot's test](https://github.com/ffang/camel-spring-boot-apache/commit/e43b1554dd9a38cbbe3465bf46e108596464994b) by @ffang is implicitly using SOAPBinding.ParameterStyle.BARE, rather than WRAPPED, so the marshaling is a bit different. I should try whether setting to BARE changes anything in my test.

**Comment by ppalaga** [comment]
Fixed via https://github.com/quarkiverse/quarkus-cxf/pull/791
