### ISSUE TITLE
Release workflow fails in `Push tags` step

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#592]
This is the step failing https://github.com/quarkiverse/quarkus-cxf/blob/1.5.6/.github/workflows/release.yml#L68-L72 : 

```
      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
```

and here is the output: https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937

```
1s
1s
Run ad-m/github-push-action@v0.6.0
  with:
    github_token: ***
    tags: true
    branch: master
    directory: .
  env:
    JAVA_HOME_[1](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937#step:10:1)1.0.17_x64: /opt/hostedtoolcache/jdk/11.0.17/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.17/x64
    JAVA_HOME_11_0_17_X64: /opt/hostedtoolcache/jdk/11.0.17/x64
Started: bash /home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.sh
Push to branch master
To https://github.com/quarkiverse/quarkus-cxf.git
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://github.com/quarkiverse/quarkus-cxf.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (events.js:314:[2](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937#step:10:2)0)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (events.js:[3](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937#step:10:3)1[4](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937#step:10:4):20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:[5](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3385044601/jobs/5622732937#step:10:5))
```

It does not seem to cause any harm because I guess the previous push step already implictly pushes the tag https://github.com/quarkiverse/quarkus-cxf/blob/1.5.6/.github/workflows/release.yml#L62-L66

@gastaldi I'd just remove the last push step unless there is some sound reason to keep it?

**Comment by gastaldi** [comment]
@ppalaga if tags are being pushed in the previous step I see no reason to keep it. Go ahead and remove it, I'll remove it from the template
