### ISSUE TITLE
AmbiguousResolutionException when CxfHandler is looking up features or interceptors via CDI.current().select(classObj).get()

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#610]
In Camel Quarkus we often configure CXF service endpoints programmatically, using CDI to lookup features and interceptors. We often use `@Named` to keep apart multiple beans of the same type, e.g.:

```
    @Inject
    @Named("loggingFeatureClient")
    LoggingFeature loggingFeature;

    @Produces
    @ApplicationScoped
    @Named("loggingFeatureClient")
    public LoggingFeature loggingFeature() {
        final LoggingFeature result = new LoggingFeature();
        result.setPrettyLogging(true);
        return result;
    }

    @Produces
    @SessionScoped
    @Named
    CxfEndpoint soapClientEndpoint() {
        final CxfEndpoint result = new CxfEndpoint();
        result.setServiceClass(CalculatorService.class);
        ...
        result.getFeatures().add(loggingFeature);
        return result;
    }


// and in some other class


    @Inject
    @Named("loggingMtomFeatureClient")
    LoggingFeature loggingFeature;


    @Produces
    @ApplicationScoped
    @Named("loggingMtomFeatureClient")
    public LoggingFeature loggingFeature() {
        final LoggingFeature result = new LoggingFeature();
        result.setPrettyLogging(true);
        return result;
    }

    @Produces
    @ApplicationScoped
    @Named
    CxfEndpoint soapMtomDisabledServerPojoModeEndpoint() {
        final CxfEndpoint result = new CxfEndpoint();
        result.getFeatures().add(loggingFeature);
        ...
        return result;
    }

```

When an additional CXF endpoint is configured using `application.properties` like this

```
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".implementor=org.apache.camel.quarkus.component.cxf.soap.it.ws.trust.sts.SampleSTS
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".features=org.apache.cxf.ext.logging.LoggingFeature
```

then the application fails at start with the following stacktrace:

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:696)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:253)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:250)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:592)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:640)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        ... 36 more
Caused by: javax.enterprise.inject.AmbiguousResolutionException: Beans: [PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.cxf.soap.wss.client.it.CxfSoapWssClientRoutes, id=c1013154fb9effc777ecc3765722e14e0795c6a5], PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.cxf.soap.mtom.awt.it.CxfSoapMtomAwtRoutes, id=a36a51b3248b51a31e9ccebde12b069eee8ca5f9], PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.cxf.soap.mtom.it.CxfSoapMtomRoutes, id=add80aae18d0cce6e348c281b11ebb76f7d6d245], PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.cxf.soap.server.it.CxfSoapRoutes, id=c17bf5d942cef6375cd7df1e8a719a66898cd928], PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.cxf.soap.client.it.CxfSoapClientRoutes, id=5f7b742b691d8460acf378da549657c0453a4a2e]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:194)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:212)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:97)
        at io.quarkiverse.cxf.transport.CxfHandler.getInstance(CxfHandler.java:181)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:118)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:146)
        at io.quarkus.deployment.steps.CxfEndpointImplementationProcessor$startRoute153619287.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.CxfEndpointImplementationProcessor$startRoute153619287.deploy(Unknown Source)
        ... 52 more
```

I think the failure per se is correct, because we really do not know which of the multiple beans should be selected for the endpoint configured via `application.properties`. If so, then we need to improve the error message. We should at least mention looking up which type for plugging into which endpoint failed. This is doable, all the required info is there in the code. 

A possible workaround is to create a new subtype of the given feature/interceptor and use that one in application properties:

```
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".implementor=org.apache.camel.quarkus.component.cxf.soap.it.ws.trust.sts.SampleSTS
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".features=org.apache.camel.quarkus.component.cxf.soap.it.ws.trust.server.StsLoggingFeature
```

```
package org.apache.camel.quarkus.component.cxf.soap.it.ws.trust.server;

import javax.enterprise.context.ApplicationScoped;
import org.apache.cxf.ext.logging.LoggingFeature;

@ApplicationScoped
public class StsLoggingFeature extends LoggingFeature {
    public StsLoggingFeature() {
        this.setPrettyLogging(true);
    }
}
```

We may want to mention the workaround in the error message.

Another possible improvement for the end users could be that we would allow setting named beans in `application.properties`, something like 

```
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".implementor=org.apache.camel.quarkus.component.cxf.soap.it.ws.trust.sts.SampleSTS
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".features=#myLoggingFeature
```

```
    @Produces
    @ApplicationScoped
    @Named("myLoggingFeature")
    public LoggingFeature loggingFeature() {
        final LoggingFeature result = new LoggingFeature();
        result.setPrettyLogging(true);
        return result;
    }

```

**Comment by ppalaga** [comment]
The error message was improved in https://github.com/quarkiverse/quarkus-cxf/pull/611

**Comment by famod** [comment]
There is a certain connection to #595 which would also require `@Named` support.

I was just wondering whether  we really need that `#` prefix.
Without it we'd need to treat it as a FQCN first, falling back to `@Named` eventually. I don't see a big issue in that but sure, `#` makes it more explicit.

**Comment by ppalaga** [comment]
I used `#myNamedBean` without too much thinking and then realized that the convention comes from Camel and is perhaps not that widespread elsewhere. Esp. I do not think I ever saw this notation in Quarkus. 

Let's call @mkouba to find the best way forward.

@mkouba, we are looking for a way to reference a `@Named` bean from `application.properties`. The place where we would like to use it currently supports fully qualified type names that are looked up in the CDI container. Hence we need a way to distinguish the `@Named` and fully qualified type name. Do you happen to know of any convention already present in Quarkus that we could use here?

**Comment by mkouba** [comment]
> Do you happen to know of any convention already present in Quarkus that we could use here?

I'm not aware of any such convention.

So the `quarkus.cxf.endpoint.features` config property currently represents a list of fully qualified class names? `org.acme.Foo#loggingFoo` where the part after `#` represents the name of the bean seems to be ok.

**Comment by ppalaga** [comment]
Thanks for the feedback, @mkouba. 

I was rather thinking of introducing 

```
quarkus.cxf.endpoint."/jaxws-samples-wsse-policy-trust-sts".features=#myNamedFeature,#myOtherNamedFeature,org.my.fully.QualifiedFeature
```

without the type prefix in case of named beans, because we cast all the named beans to some single abstract type anyway, so their particular subtype is not important.

**Comment by mkouba** [comment]
> without the type prefix in case of named beans, because we cast all the named beans to some single abstract type anyway, so their particular subtype is not important.

Sure, if you know the type then a list of names is ok. However, keep in mind that `@Named` is a bit tricky. It's a qualifier but at the same time a bean that declares `@Named` but no other qualifier has the `@Default` qualifier as well.
