### ISSUE TITLE
Mandrel 22.3.0.1-Final-java17: Class io.quarkiverse.cxf.it.server.Fruit[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#695]
With this newest Mandrel image 

```
Pulling from quarkus/ubi-quarkus-mandrel-builder-image
[INFO] [stdout] Digest: sha256:e9f0a3b44ec4afbbd19968cf834f922e62b824f9b97e9cdcc9a03de5a04d1496
[INFO] [stdout] Status: Image is up to date for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
[INFO] [stdout] quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
```

The following error started occurring:

```
[INFO] Running io.quarkiverse.cxf.it.server.FaultyHelloServiceIT
[INFO] [stdout] Executing "/home/ppalaga/orgs/cxf/quarkiverse-cxf/integration-tests/server/target/quarkus-cxf-integration-test-server-1.8.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/ppalaga/orgs/cxf/quarkiverse-cxf/integration-tests/server/target/quarkus.log -Dquarkus.log.file.enable=true"
[INFO] [stdout] __  ____  __  _____   ___  __ ____  ______ 
[INFO] [stdout]  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
[INFO] [stdout]  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
[INFO] [stdout] --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
[INFO] [stdout] 2023-01-23 19:10:02,401 INFO  [org.apa.cxf.end.ServerImpl] (main) Setting the server's publish address to be /faulty-hello
[INFO] [stdout] 2023-01-23 19:10:02,402 INFO  [io.qua.cxf.tra.CxfHandler] (main) Web Service io.quarkiverse.cxf.it.server.FaultyHelloServiceImpl on /soap available.
[INFO] [stdout] 2023-01-23 19:10:02,404 INFO  [org.apa.cxf.end.ServerImpl] (main) Setting the server's publish address to be /greeting-no-intf
[INFO] [stdout] 2023-01-23 19:10:02,404 INFO  [io.qua.cxf.tra.CxfHandler] (main) Web Service io.quarkiverse.cxf.it.server.GreetingWebServiceNoIntf on /soap available.
[INFO] [stdout] 2023-01-23 19:10:02,409 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.IllegalArgumentException: Class io.quarkiverse.cxf.it.server.Fruit[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
[INFO] [stdout]         at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:345)
[INFO] [stdout]         at org.apache.cxf.jaxb.JAXBContextInitializer.begin(JAXBContextInitializer.java:151)
[INFO] [stdout]         at org.apache.cxf.service.ServiceModelVisitor.visitOperation(ServiceModelVisitor.java:109)
[INFO] [stdout]         at org.apache.cxf.service.ServiceModelVisitor.visitOperation(ServiceModelVisitor.java:130)
[INFO] [stdout]         at org.apache.cxf.service.ServiceModelVisitor.walk(ServiceModelVisitor.java:74)
[INFO] [stdout]         at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:347)
[INFO] [stdout]         at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:87)
[INFO] [stdout]         at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
[INFO] [stdout]         at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693)
[INFO] [stdout]         at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529)
[INFO] [stdout]         at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
[INFO] [stdout]         at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
[INFO] [stdout]         at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
[INFO] [stdout]         at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
[INFO] [stdout]         at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
[INFO] [stdout]         at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:141)
[INFO] [stdout]         at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:146)
[INFO] [stdout]         at io.quarkus.deployment.steps.CxfEndpointImplementationProcessor$startRoute1357177498.deploy_0(Unknown Source)
[INFO] [stdout]         at io.quarkus.deployment.steps.CxfEndpointImplementationProcessor$startRoute1357177498.deploy(Unknown Source)
[INFO] [stdout]         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[INFO] [stdout]         at io.quarkus.runtime.Application.start(Application.java:101)
[INFO] [stdout]         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
[INFO] [stdout]         at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[INFO] [stdout] 
```

This used to work [two days ago](https://github.com/quarkiverse/quarkus-cxf/actions/runs/3966854832/jobs/6798256940#step:5:256) with this older Mandrel image:

```
Digest: sha256:c71c765bd8f3fa07279e4aec1b1002d19f3f937ad1f924331e802016eb5aa768
Status: Downloaded newer image for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
```

Adding `reflect-config.json` like the following helps:

```
[
    {
        "name": "io.quarkiverse.cxf.it.server.Fruit[]",
        "unsafeAllocated": true
    }
]
```

See also 
* https://github.com/quarkusio/quarkus/issues/29922
* https://github.com/apache/camel-quarkus/issues/4284

**Comment by ppalaga** [comment]
@zakkak @galderz is this a known regression?

**Comment by zakkak** [comment]
I am not able to pull `sha256:c71c765bd8f3fa07279e4aec1b1002d19f3f937ad1f924331e802016eb5aa768`, but nevertheless this issue is pretty weird given that the two builder images are (probably) using the same Mandrel build (22.3.0.1-Final) which means that the only changes between the two should be in the dockerized OS.

Can you please try with the latest `quarkus/ubi-quarkus-mandrel-builder-image` (based on `22.3.1.0-Final`)?

**Comment by ppalaga** [comment]
This issue does not happen on Quarkus 3.3 anymore as shown by https://github.com/quarkiverse/quarkus-cxf/pull/970
