### ISSUE TITLE
Soap client reflection error

### ISSUE THREAD

**Issue by AlstonTsaoTSMC** [quarkiverse/quarkus-cxf#721]
Hi

I'm building a soap client with 
```
JDK 17
apache-cxf-plugin 4.0.0
quarkus-cxf 2.0.0.Alpha1
quarkus 3.0.0.Alpha4
```
It works on the demo calculator, but fail in my project. 

The wsdl file is provided as url, code gen is no problem with it. Service and port objects are initialized. Everything works until sending message out. Actually I have no idea where problem is because it doesn't show error messages, only call stacks. Anyone idea please?

```
2023-02-24 15:33:17,400 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /soap failed, error id: xxx: com.my.mfg.mfg_toy.mfgwfr_proctoy.toy_query.ToyInfoFromCellServerError_Exception: Error:
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.apache.cxf.interceptor.ClientFaultConverter.processFaultDetail(ClientFaultConverter.java:183)
	at org.apache.cxf.interceptor.ClientFaultConverter.handleMessage(ClientFaultConverter.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:70)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:35)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:829)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1726)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1592)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1389)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:689)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:528)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:439)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:354)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:312)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
	at jdk.proxy4/jdk.proxy4.$Proxy111.readToyInfoFromCellServerSync(Unknown Source)
	at com.my.GreetingResource.fetchToyInfo(GreetingResource.kt:53)
	at com.my.GreetingResource.toyInfo(GreetingResource.kt:70)
	at com.my.GreetingResource$quarkusrestinvoker$toyInfo_387cce86471d07453e15763095572569c3a883da.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

application.properties
```
cxf.ToyInfo.baseUri=http://domain.com
quarkus.cxf.client.ToyInfo.wsdl=${cxf.ToyInfo.baseUri}?wsdl
quarkus.cxf.client.ToyInfo.client-endpoint-url=${cxf.ToyInfo.baseUri}
quarkus.cxf.client.ToyInfo.service-interface=com.my.mfg.mfg_pizza.mfgwfr_proctoy.toy_query.InquireToyInfoFromCellServer
```

Kotlin source code:
```kotlin
@Path("/")
class GreetingResource {
    @CXFClient("ToyInfo")
    lateinit var toyService: InquireToyInfoFromCellServer

    private fun fetchToyInfo(toyId: String): ToyInfoFromCellServerResponse? {
        val bizObjDoc = ToyInfoFromCellServerQuery.BizObjDoc()
        val query = ToyInfoFromCellServerQuery()
       return toyService.readToyInfoFromCellServerSync(query) // <--error occurs here
    }

    @GET
    @Path("soap")
    fun toyInfo(): ToyInfoFromCellServerResponse? {
        return fetchToyInfo("123")
    }
}
```

**Comment by shumonsharif** [comment]
I'm wondering if your service is returning a soap fault; are you able to log the payloads?

https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/reference/payload-logging-feature.html

**Comment by AlstonTsaoTSMC** [comment]
Thanks a lot. The logging feature is really helpful for debugging. Now I found the problem: I need to set soap header like this:

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:lot="http://...">
    <soapenv:Header>
      <abc:MesToken xmlns:abc="http://abc.com/security/mes_token">
         <abc:username>USER_NAME</abc:username>
         <abc:password>PW</abc:password>
      </abc:MesToken>
    </soapenv:Header>
   <soapenv:Body>
    <!-- omit -->
   </soapenv:Body>
</soapenv:Envelope>
```

How can I add header with generated code?

**Comment by AlstonTsaoTSMC** [comment]
```xml
data class MyToken constructor (
    @field:XmlElement(name = "abc:username")
    val username: String,
    @field:XmlElement(name = "abc:password")
    val password: String
)

class SoapInterceptor: AbstractSoapInterceptor(Phase.PRE_LOGICAL) {
    private val namespace =  "http://domain.com"
    override fun handleMessage(message: SoapMessage?) {
        try {
            val myToken = MyToken("username", "password")
            val header = Header(QName(namespace,"MyToken", "abc"), myToken, JAXBDataBinding(MyToken::class.java))
            message?.headers?.add(header)
        } catch (e: Exception) {
            Log.error(e.toString(), e)
        }
    }
}
```



```
val proxy = ClientProxy.getClient(toyService) // injected generated service object
proxy.outInterceptors.add(SoapInterceptor())
```
