### ISSUE TITLE
build failed on quarkus main

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkus-cxf#936]
status:
https://status.quarkus.io/

automatic ticket open for failed CI : 
https://github.com/quarkiverse/quarkus-dashbuilder/actions/runs/5460656926

LOGS:
```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-dashbuilder-docs: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkiverse.dashbuilder.deployment.DashbuilderProcessor#buildDashbuilderWebApp threw an exception: java.lang.NullPointerException
Error:  	at io.quarkiverse.dashbuilder.deployment.DashbuilderProcessor.buildDashbuilderWebApp(DashbuilderProcessor.java:157)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
Error:  	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  -> [Help 1]
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-dashbuilder-integration-tests: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkiverse.dashbuilder.deployment.DashbuilderProcessor#buildDashbuilderWebApp threw an exception: java.lang.NullPointerException
Error:  	at io.quarkiverse.dashbuilder.deployment.DashbuilderProcessor.buildDashbuilderWebApp(DashbuilderProcessor.java:157)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
Error:  	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by dufoli** [comment]
it seems to be not related to cxf .

**Comment by dufoli** [comment]
not related to cxf...
