### ISSUE TITLE
native compilation failure io.quarkiverse.cxf:quarkus-cxf:jar:2.2.0

### ISSUE THREAD

**Issue by c-schmitz-tsystems** [quarkiverse/quarkus-cxf#944]
we use the lts version of quarkus 3.2.2.Final together with quarkus-cfx version 2.2.0. we've got the following error in native compilation (combination of quarkus 2.16.8.Final and quarkus-cfx version 1.7.2 works). It seems to be related to the following (new) package:

```
[INFO] +- io.quarkiverse.cxf:quarkus-cxf:jar:2.2.0:compile
[INFO] |  +- io.quarkiverse.cxf:quarkus-cxf-saaj:jar:2.2.0:compile
[INFO] |  |  \- com.sun.xml.messaging.saaj:saaj-impl:jar:2.0.1:compile
[INFO] |  |     +- jakarta.xml.soap:jakarta.xml.soap-api:jar:2.0.1:compile
[INFO] |  |     \- org.jvnet.staxex:stax-ex:jar:2.0.1:compile
[INFO] |  +- io.quarkiverse.cxf:quarkus-cxf-axiom-api-stub:jar:2.2.0:compile
[INFO] |  +- io.quarkiverse.cxf:quarkus-cxf-woodstox:jar:2.2.0:compile
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:4.0.2:compile
[INFO] |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:4.0.2:compile
[INFO] |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.3.0:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:4.0.2:compile
[INFO] |  |  |  +- jakarta.jws:jakarta.jws-api:jar:3.0.0:compile
[INFO] |  |  |  +- jakarta.xml.ws:jakarta.xml.ws-api:jar:3.0.1:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:4.0.2:compile
[INFO] |  |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:4.0.2:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:4.0.2:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:4.0.2:compile
[INFO] |  |  |  \- org.eclipse.angus:angus-mail:jar:1.0.0:compile
[INFO] |  |  |     \- jakarta.mail:jakarta.mail-api:jar:2.1.0:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-ws-addr:jar:4.0.2:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-policy:jar:4.0.2:compile
[INFO] |  |  |     \- org.apache.neethi:neethi:jar:3.2.0:compile
**[INFO] |  |  \- org.eclipse.angus:angus-activation:jar:2.0.1:compile
[INFO] |  |     \- jakarta.activation:jakarta.activation-api:jar:2.1.2:compile**
```

Here the native error:

```
The build process encountered an unexpected error:
com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    class: org.eclipse.angus.activation.nativeimage.AngusActivationFeature
  reachable through:
    object: [Ljava.lang.Class;@3dfeee8d  of class: java.lang.Class[]
    object: com.oracle.svm.core.code.ImageCodeInfo@412dea41  of class: com.oracle.svm.core.code.ImageCodeInfo
    root: com.oracle.svm.core.code.ImageCodeInfo.prepareCodeInfo()
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:76)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:702)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

**Comment by ppalaga** [comment]
Thanks for the report, @c-schmitz-tsystems! Would you mind posting a minimal reproducer?

**Comment by ppalaga** [comment]
@c-schmitz-tsystems are you using Quarkus Platform BOMs as suggested in https://docs.quarkiverse.io/quarkus-cxf/dev/user-guide/create-project.html#dependency-management ? The recommendation changed a bit recently.

**Comment by ppalaga** [comment]
Closing for lack of feedback. @c-schmitz-tsystems please feel free to reopen providing the requested info.
