### ISSUE TITLE
Netty Http2Exception: Flow control window exceeded for stream: 0 when sending a ~64 KiB attachment

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-cxf#973]
Originally reported as https://github.com/quarkiverse/quarkus-cxf/discussions/971 by @xperjon

There are two slightly different ways to reproduce the issue. Both are present in https://github.com/quarkiverse/quarkus-cxf/pull/974

1. Send an attachment over 64 KiB - see MtomTest.largeAttachment() in #971 
2. Soak the endpoint with requests slightly under 64 KiB - see MtomTest.soak() in #971 

In both cases, the stack trace (on the server side) is the following: 

```
WARN  [org.apa.cxf.pha.PhaseInterceptorChain] (executor-thread-1) Interceptor for {https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test/mtom}MtomService has thrown exception, unwinding now: java.lang.RuntimeException: java.io.IOException: java.io.IOException: io.netty.handler.codec.http2.Http2Exception: Flow control window exceeded for stream: 0
        at org.apache.cxf.attachment.LazyAttachmentCollection$1.hasNext(LazyAttachmentCollection.java:108)
        at org.apache.cxf.binding.soap.saaj.SAAJInInterceptor.handleMessage(SAAJInInterceptor.java:209)
        at org.apache.cxf.jaxws.handler.soap.SOAPMessageContextImpl.getMessage(SOAPMessageContextImpl.java:79)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.getOpQName(SOAPHandlerInterceptor.java:318)
        at org.apache.cxf.jaxws.handler.AbstractJAXWSHandlerInterceptor.setupBindingOperationInfo(AbstractJAXWSHandlerInterceptor.java:110)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.createProtocolMessageContext(SOAPHandlerInterceptor.java:253)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessageInternal(SOAPHandlerInterceptor.java:158)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessage(SOAPHandlerInterceptor.java:121)
        at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessage(SOAPHandlerInterceptor.java:70)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:233)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:207)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:159)
        at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:245)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:182)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:46)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:577)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: java.io.IOException: io.netty.handler.codec.http2.Http2Exception: Flow control window exceeded for stream: 0
        at io.quarkus.vertx.http.runtime.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:255)
        at io.quarkus.vertx.http.runtime.VertxInputStream.readIntoBuffer(VertxInputStream.java:122)
        at io.quarkus.vertx.http.runtime.VertxInputStream.read(VertxInputStream.java:84)
        at io.quarkiverse.cxf.transport.VertxHttpServletRequest$1.read(VertxHttpServletRequest.java:122)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
        at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:182)
        at org.apache.cxf.attachment.MimeBodyPartInputStream.read(MimeBodyPartInputStream.java:80)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at org.apache.cxf.attachment.DelegatingInputStream.read(DelegatingInputStream.java:95)
        at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:222)
        at org.apache.cxf.helpers.IOUtils.copy(IOUtils.java:179)
        at org.apache.cxf.attachment.AttachmentDeserializer.cache(AttachmentDeserializer.java:268)
        at org.apache.cxf.attachment.AttachmentDeserializer.cacheStreamedAttachments(AttachmentDeserializer.java:241)
        at org.apache.cxf.attachment.AttachmentDeserializer.readNext(AttachmentDeserializer.java:222)
        at org.apache.cxf.attachment.LazyAttachmentCollection$1.hasNext(LazyAttachmentCollection.java:101)
        ... 28 more
Caused by: java.io.IOException: io.netty.handler.codec.http2.Http2Exception: Flow control window exceeded for stream: 0
        at io.quarkus.vertx.http.runtime.VertxInputStream$VertxBlockingInput$2.handle(VertxInputStream.java:202)
        at io.quarkus.vertx.http.runtime.VertxInputStream$VertxBlockingInput$2.handle(VertxInputStream.java:198)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.http.impl.HttpEventHandler.handleException(HttpEventHandler.java:89)
        at io.vertx.core.http.impl.Http2ServerRequest.notifyException(Http2ServerRequest.java:133)
        at io.vertx.core.http.impl.Http2ServerRequest.handleException(Http2ServerRequest.java:118)
        at io.vertx.core.http.impl.Http2ServerStream.handleException(Http2ServerStream.java:177)
        at io.vertx.core.http.impl.Http2ConnectionBase.lambda$onConnectionError$1(Http2ConnectionBase.java:120)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.http.impl.Http2ConnectionBase.onConnectionError(Http2ConnectionBase.java:120)
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onConnectionError(VertxHttp2ConnectionHandler.java:158)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:654)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.exceptionCaught(Http2ConnectionHandler.java:580)
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.exceptionCaught(VertxHttp2ConnectionHandler.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:133)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 more
Caused by: io.netty.handler.codec.http2.Http2Exception: Flow control window exceeded for stream: 0
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:152)
        at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.receiveFlowControlledFrame(DefaultHttp2LocalFlowController.java:429)
        at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.receiveFlowControlledFrame(DefaultHttp2LocalFlowController.java:273)
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:412)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        ... 30 more
```

Some observations:

* Setting `quarkus.http.http2=false` on the server causes a slightly different exception on a different place in netty code, ~hence HTTP/1 does not work either.~ Update 2023-09-01: `quarkus.http.http2=false` is actually a valid workaround for the current issue. The failure that happens with `quarkus.http.http2=false` is a different issue, namely https://github.com/quarkiverse/quarkus-cxf/issues/992 
* Enlarging the max payload on the server side via `quarkus.http.limits.max-body-size` does not change anything
* Both tests fail on Quarkus 3.0 through Quarkus 3.3 (QCXF 2.0 - 2.3)
* The good news is that both tests pass on Quarkus 2.13 (see https://github.com/quarkiverse/quarkus-cxf/pull/975 ) and 2.16 (QCXF 1.5 and 1.7)

## Possible workarounds

* Setting `quarkus.http.http2=false` on the server, but be aware that you may still face https://github.com/quarkiverse/quarkus-cxf/issues/992
* @shumonsharif found that switching the client to Async HTTP Client v5 makes the issue disappear too - see https://github.com/quarkiverse/quarkus-cxf/discussions/971#discussioncomment-6770012
* The root cause https://github.com/eclipse-vertx/vert.x/pull/4802 is fixed in Vert.x 4.4.5, hence importing `vertx-dependencies` before Quarkus Platform BOMs solves the issue too:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-dependencies</artifactId>
                <version>4.4.5</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <!-- Quarkus Platfrom BOMs come here -->

        </dependencies>
    </dependencyManagement>
```

**Comment by ppalaga** [comment]
Reported on Vert.X Core as suggested by @cescoffier https://github.com/eclipse-vertx/vert.x/issues/4814

**Comment by ppalaga** [comment]
Blocked by https://github.com/quarkusio/quarkus/pull/35656

**Comment by cescoffier** [comment]
@ppalaga I mentioned it yesterday; it's not going to be this PR that will be backported to 3.2.
I'm going to split this one into 2 PRs:

- the strictly required changes that can be backported to 3.2
- the update of deprecated usages - these touch many files, so we won't backport.

**Comment by ppalaga** [comment]
Upgrade to Vert.x 4.4.5 happened in Quarkus 3.4.0 via https://github.com/quarkusio/quarkus/pull/35700

**Comment by ppalaga** [comment]
Hopefully Quarkus 3.2 (LTS) [gets fixed too](https://github.com/quarkusio/quarkus/pull/35700#issuecomment-1722417721).
